USE GESTION_TALLER;

IF OBJECT_ID('TR_SGT_PERSONA_CALCULAR_EDAD', 'TR') IS NOT NULL
    DROP TRIGGER TR_SGT_PERSONA_CALCULAR_EDAD;
GO

CREATE TRIGGER TR_SGT_PERSONA_CALCULAR_EDAD
ON SGT_PERSONA_TALLER
AFTER INSERT, UPDATE
AS BEGIN
	SET NOCOUNT ON;
	--servira para contar la edad del usuario calculando segun su nacimiento.
	UPDATE P
	SET EDAD = DATEDIFF(YEAR, I.FEC_NACIMIENTO, GETDATE())
	FROM SGT_PERSONA_TALLER P
		INNER JOIN INSERTED I ON P.ID_PERSONA = I.ID_PERSONA
	WHERE P.FEC_NACIMIENTO IS NOT NULL;
END;
GO