USE [GESTION_TALLER]
GO

DECLARE @CONTRASENA VARCHAR (255)
SET @CONTRASENA = '123123123';

DECLARE @CONTRASENA_HASH VARCHAR (255)
SET @CONTRASENA_HASH = CONVERT(VARCHAR(255), HASHBYTES('SHA2_256', @CONTRASENA));

UPDATE [dbo].[SGT_PERSONA_TALLER]
   SET CONTRASENA_HASH = @CONTRASENA_HASH
 WHERE [ID_PERSONA] = 2
GO


