-- Dar de baja a un tallerista (cambiar estado en SGT_PERSONA_TALLER? O en SGT_PROFESOR? Según tu modelo, la baja podría ser IND_ACTIVO en PERSONA)
CREATE PROCEDURE SUSPENDER_TALLERISTA
    @ID_PROFESOR INT,
    @USUARIO_MODIFICA VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE P
    SET P.IND_ACTIVO = 0,
        P.AUD_USUARIO_MODIFICA = @USUARIO_MODIFICA,
        P.AUD_FEC_MODIFICA = GETDATE()
    FROM SGT_PERSONA_TALLER P
    INNER JOIN SGT_PROFESOR PR ON P.ID_PERSONA = PR.ID_PERSONA
    WHERE PR.ID_PROFESOR = @ID_PROFESOR;
END;
GO