USE GESTION_TALLER;

IF OBJECT_ID('AC_ESTUDIANTE', 'P') IS NOT NULL
    DROP PROCEDURE AC_ESTUDIANTE;
GO

CREATE PROCEDURE AC_ESTUDIANTE
 @ID_TALLER NUMERIC(10),
 @ID_ESTUDIANTE NUMERIC(10),
 @PRONOM_ESTUDIANTE VARCHAR(50),
 @YEAR_PROCESO INT,
 @IND_ESTADO_INTEGRANTE INT,
 @FEC_RETIRO DATETIME,
 @OBSERVACION TEXT,
 @FEC_REINCORPORACION DATETIME,
 @AUD_USUARIO_MODIFICA VARCHAR(20),
 @AUD_FEC_MODIFICA DATETIME
AS BEGIN
--TENGO QUE ARREGLAR PARA QUE BUSQUE POR ID ESTUDIANTE JUNTANDO ESTUDIANTE Y INTEGRANTE TALLER, NO ES NECESARIO QUE FILTRE POR AÑO , ESO LO HARE EN EL GET
UPDATE SGT_INTEGRANTE_TALLER
SET PRONOM_ESTUDIANTE=@PRONOM_ESTUDIANTE,
	YEAR_PROCESO=@YEAR_PROCESO,
	IND_ESTADO_INTEGRANTE=@IND_ESTADO_INTEGRANTE,
	FEC_RETIRO=@FEC_RETIRO,
	OBSERVACION=@OBSERVACION,
	FEC_REINCORPORACION=@FEC_REINCORPORACION,
	AUD_USUARIO_MODIFICA=@AUD_USUARIO_MODIFICA,
	AUD_FEC_MODIFICA=ISNULL(@AUD_FEC_MODIFICA, GETDATE())
WHERE ID_ESTUDIANTE=@ID_ESTUDIANTE 
  AND ID_TALLER=@ID_TALLER 
  AND YEAR_PROCESO=@YEAR_PROCESO;

IF @@ROWCOUNT > 0
    SELECT 'Se han actualizado los datos del/la "Estudiante" al sistema' AS RESULTADO;
ELSE
    SELECT 'No se encontró el registro especificado' AS RESULTADO;
END;

--CREATE TABLE [dbo].[SGT_ESTUDIANTE](
--	[ID_ESTUDIANTE] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
--	[ID_PERSONA] [numeric](10, 0) NOT NULL,
--	[AUD_USUARIO_INGRESO] [varchar](20) NOT NULL,
--	[AUD_FEC_INGRESO] [datetime] NOT NULL,
--	[AUD_USUARIO_MODIFICA] [varchar](20) NOT NULL,
--	[AUD_FEC_MODIFICA] [datetime] NOT NULL,
-- CONSTRAINT [PK_SGT_ALUMNO] PRIMARY KEY CLUSTERED 

--CREATE TABLE [dbo].[SGT_INTEGRANTE_TALLER](
--	[ID_INTEGRANTE_TALLER] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
--	[ID_TALLER] [numeric](10, 0) NOT NULL,
--	[ID_ESTUDIANTE] [numeric](10, 0) NOT NULL,
--	[PRONOM_ESTUDIANTE] [varchar](50) NULL,
--	[YEAR_PROCESO] [int] NOT NULL,
--	[IND_ESTADO_INTEGRANTE] [int] NOT NULL,
--	[FEC_INSCRIPCION] [datetime] NOT NULL,
--	[FEC_RETIRO] [datetime] NOT NULL,
--	[OBSERVACION] [text] NOT NULL,
--	[FEC_REINCORPORACION] [datetime] NOT NULL,
--	[AUD_USUARIO_INGRESO] [varchar](20) NOT NULL,
--	[AUD_FEC_INGRESO] [datetime] NOT NULL,
--	[AUD_USUARIO_MODIFICA] [varchar](20) NOT NULL,
--	[AUD_FEC_MODIFICA] [datetime] NOT NULL,
-- CONSTRAINT [PK_SGT_ALUMNO_TALLER] PRIMARY KEY CLUSTERED 