USE GESTION_TALLER;

IF OBJECT_ID('AC_TALLERISTAS', 'P') IS NOT NULL
    DROP PROCEDURE AC_TALLERISTAS;
GO

CREATE PROCEDURE AC_TALLERISTAS
    @ID_PROFESOR NUMERIC(10),
    @NOMBRE_PERSONA VARCHAR(50),
    @APELLIDO_PATERNO VARCHAR(50),
    @APELLIDO_MATERNO VARCHAR(50),
    @GENERO INT,
    @TELEFONO VARCHAR(20),
    @CORREO_ELECTRONICO VARCHAR(100),
    @TELEFONO_CONTACTO VARCHAR(20),
    @NOMBRE_CONTACTO VARCHAR(100),
    @CORREO_CONTACTO VARCHAR(100),
    @PROFESION VARCHAR(500),
    @RESUMEN_CURRICULAR VARCHAR(500),
    @OBSERVACION VARCHAR(255),
    @ID_PAIS INT,
    @ID_COMUNA INT,
    @VILLA VARCHAR(100),
    @NRO_DPTO VARCHAR(10),
    @NRO_BLOCK VARCHAR(10),
    @NRO_CALLE VARCHAR(10),
    @CALLE VARCHAR(100),
    @AUD_USUARIO_MODIFICA_PT VARCHAR(20),
    @AUD_USUARIO_MODIFICA_P VARCHAR(20)
AS
BEGIN
	SET NOCOUNT ON;
    DECLARE @ID_PERSONA NUMERIC(10);
    DECLARE @INICIADOR BIT = 0;

	SELECT @ID_PERSONA = ID_PERSONA FROM SGT_PROFESOR WHERE ID_PROFESOR = @ID_PROFESOR;

	BEGIN TRY
		IF @@TRANCOUNT = 0
        BEGIN
            BEGIN TRANSACTION;
            SET @INICIADOR = 1;
        END

		UPDATE PT
        SET PT.NOMBRE_PERSONA = ISNULL(@NOMBRE_PERSONA, '-'),
            PT.APELLIDO_PATERNO = ISNULL(@APELLIDO_PATERNO, '-'),
            PT.APELLIDO_MATERNO = ISNULL(@APELLIDO_MATERNO, '-'),
            PT.GENERO = CASE WHEN @GENERO IN (0,1,2,3,4) THEN @GENERO ELSE PT.GENERO END,
            PT.TELEFONO = ISNULL(@TELEFONO, '-'),
            PT.CORREO_ELECTRONICO = ISNULL(@CORREO_ELECTRONICO, '-'),
            PT.TELEFONO_CONTACTO = ISNULL(@TELEFONO_CONTACTO, '-'),
            PT.NOMBRE_CONTACTO = ISNULL(@NOMBRE_CONTACTO, '-'),
            PT.CORREO_CONTACTO = ISNULL(@CORREO_CONTACTO, '-'),
            PT.OBSERVACION = ISNULL(@OBSERVACION, '-'),
            PT.ID_PAIS = @ID_PAIS,
            PT.ID_COMUNA = @ID_COMUNA,
            PT.VILLA = ISNULL(@VILLA, '-'),
            PT.NRO_DPTO = ISNULL(@NRO_DPTO, '-'),
            PT.NRO_BLOCK = ISNULL(@NRO_BLOCK, '-'),
            PT.NRO_CALLE = ISNULL(@NRO_CALLE, '-'),
            PT.CALLE = ISNULL(@CALLE, '-'),
            PT.AUD_USUARIO_MODIFICA = @AUD_USUARIO_MODIFICA_PT,
            PT.AUD_FEC_MODIFICA = GETDATE()
        FROM SGT_PERSONA_TALLER PT
        WHERE PT.ID_PERSONA = @ID_PERSONA
          AND EXISTS (
              SELECT @NOMBRE_PERSONA,@APELLIDO_PATERNO,@APELLIDO_MATERNO,@GENERO,@TELEFONO,@CORREO_ELECTRONICO,@TELEFONO_CONTACTO,@NOMBRE_CONTACTO,@CORREO_CONTACTO,@OBSERVACION,@ID_PAIS,@ID_COMUNA,@VILLA,@NRO_DPTO,@NRO_BLOCK,@NRO_CALLE,@CALLE
              EXCEPT
              SELECT PT.NOMBRE_PERSONA,PT.APELLIDO_PATERNO,PT.APELLIDO_MATERNO,PT.GENERO,PT.TELEFONO,PT.CORREO_ELECTRONICO,PT.TELEFONO_CONTACTO,PT.NOMBRE_CONTACTO,PT.CORREO_CONTACTO,PT.OBSERVACION,PT.ID_PAIS,PT.ID_COMUNA,PT.VILLA,PT.NRO_DPTO,PT.NRO_BLOCK,PT.NRO_CALLE,PT.CALLE
          );

		UPDATE P
        SET P.PROFESION = ISNULL(@PROFESION, '-'),
            P.RESUMEN_CURRICULAR = ISNULL(@RESUMEN_CURRICULAR, '-'),
            P.AUD_USUARIO_MODIFICA = @AUD_USUARIO_MODIFICA_P,
            P.AUD_FEC_MODIFICA = GETDATE()
        FROM SGT_PROFESOR P
        WHERE P.ID_PROFESOR = @ID_PROFESOR
          AND EXISTS (
              SELECT @PROFESION,@RESUMEN_CURRICULAR
              EXCEPT
              SELECT P.PROFESION,P.RESUMEN_CURRICULAR
          );
        IF @INICIADOR = 1 AND @@TRANCOUNT > 0
		    COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT >0
			ROLLBACK TRANSACTION;
        DECLARE @ERROR NVARCHAR(4000) = ERROR_MESSAGE();
        RAISERROR (@ERROR, 16, 1);
	END CATCH
END;
-- la base de datos es una sql server 2008 r2 , el tema es que necesito hacer un upd a 3 tablas , profesor que se conecta a administracion y este se conecta a taller