USE GESTION_TALLER;

IF OBJECT_ID('AC_ESTUDIANTE', 'P') IS NOT NULL
    DROP PROCEDURE AC_ESTUDIANTE;
GO

CREATE PROCEDURE AC_ESTUDIANTE
    @ID_ESTUDIANTE NUMERIC(10),
    @NOMBRE_PERSONA VARCHAR(50),
    @APELLIDO_PATERNO VARCHAR(50),
    @APELLIDO_MATERNO VARCHAR(50),
    @PRONOM_ESTUDIANTE VARCHAR(50),
    @GENERO INT,
    @TELEFONO VARCHAR(20),
    @CORREO_ELECTRONICO VARCHAR(100),
    @TELEFONO_CONTACTO VARCHAR(20),
    @NOMBRE_CONTACTO VARCHAR(100),
    @CORREO_CONTACTO VARCHAR(100),
    @OBSERVACION VARCHAR(255),
    @IND_ESTADO_INTEGRANTE INT,
    @ID_PAIS INT,
    @ID_COMUNA INT,
    @VILLA VARCHAR(100),
    @NRO_DPTO VARCHAR(10),
    @NRO_BLOCK VARCHAR(10),
    @NRO_CALLE VARCHAR(10),
    @CALLE VARCHAR(100),
    @FEC_INGRESO DATETIME,
    @FEC_RETIRO DATETIME,
    @FEC_REINCORPORACION DATETIME,
    @AUD_USUARIO_MODIFICA VARCHAR(20)
AS 
BEGIN
    SET NOCOUNT ON;
    DECLARE @ID_PERSONA NUMERIC(10);
    DECLARE @INICIADOR BIT = 0;

	SELECT @ID_PERSONA = ID_PERSONA FROM SGT_ESTUDIANTE WHERE ID_ESTUDIANTE = @ID_ESTUDIANTE;

	BEGIN TRY
        IF @@TRANCOUNT = 0
		BEGIN
            BEGIN TRANSACTION;
            SET @INICIADOR = 1;
        END

--UPDATE SGT_ESTUDIANTE;

    UPDATE PT
        SET PT.NOMBRE_PERSONA = ISNULL(@NOMBRE_PERSONA, '-'),
            PT.APELLIDO_PATERNO = ISNULL(@APELLIDO_PATERNO, '-'),
            PT.APELLIDO_MATERNO = ISNULL(@APELLIDO_MATERNO, '-'),
            PT.GENERO = CASE WHEN @GENERO IN (0,1,2,3,4) THEN @GENERO ELSE PT.GENERO END,
            PT.TELEFONO = ISNULL(@TELEFONO, '-'),
            PT.CORREO_ELECTRONICO = ISNULL(@CORREO_ELECTRONICO, '-'),
            PT.TELEFONO_CONTACTO = ISNULL(@TELEFONO_CONTACTO, '-'),
            PT.NOMBRE_CONTACTO = ISNULL(@NOMBRE_CONTACTO, '-'),
            PT.CORREO_CONTACTO = ISNULL(@CORREO_CONTACTO, '-'),
            PT.OBSERVACION = ISNULL(@OBSERVACION, '-'),
            PT.ID_PAIS = @ID_PAIS,
            PT.ID_COMUNA = @ID_COMUNA,
            PT.VILLA = ISNULL(@VILLA, '-'),
            PT.NRO_DPTO = ISNULL(@NRO_DPTO, '-'),
            PT.NRO_BLOCK = ISNULL(@NRO_BLOCK, '-'),
            PT.NRO_CALLE = ISNULL(@NRO_CALLE, '-'),
            PT.CALLE = ISNULL(@CALLE, '-'),
            PT.AUD_USUARIO_MODIFICA = @AUD_USUARIO_MODIFICA,
            PT.AUD_FEC_MODIFICA = GETDATE()
        FROM SGT_PERSONA_TALLER PT
        WHERE PT.ID_PERSONA = @ID_PERSONA
          AND EXISTS (
              SELECT @NOMBRE_PERSONA,@APELLIDO_PATERNO,@APELLIDO_MATERNO,@GENERO,@TELEFONO,@CORREO_ELECTRONICO,@TELEFONO_CONTACTO,@NOMBRE_CONTACTO,@CORREO_CONTACTO,@OBSERVACION,@ID_PAIS,@ID_COMUNA,@VILLA,@NRO_DPTO,@NRO_BLOCK,@NRO_CALLE,@CALLE
              EXCEPT
              SELECT PT.NOMBRE_PERSONA,PT.APELLIDO_PATERNO,PT.APELLIDO_MATERNO,PT.GENERO,PT.TELEFONO,PT.CORREO_ELECTRONICO,PT.TELEFONO_CONTACTO,PT.NOMBRE_CONTACTO,PT.CORREO_CONTACTO,PT.OBSERVACION,PT.ID_PAIS,PT.ID_COMUNA,PT.VILLA,PT.NRO_DPTO,PT.NRO_BLOCK,PT.NRO_CALLE,PT.CALLE
          );

        UPDATE IT
        SET IT.PRONOM_ESTUDIANTE = ISNULL(@PRONOM_ESTUDIANTE, 'Sin Definir'),
	        IT.IND_ESTADO_INTEGRANTE = CASE WHEN @IND_ESTADO_INTEGRANTE IN (1,2,3) THEN @IND_ESTADO_INTEGRANTE ELSE IT.IND_ESTADO_INTEGRANTE END,
	        IT.FEC_RETIRO = CONVERT(DATE, @FEC_RETIRO, 121),
	        IT.OBSERVACION = ISNULL(@OBSERVACION, '-'),
	        IT.FEC_REINCORPORACION = CONVERT(DATE, @FEC_REINCORPORACION, 121),
	        IT.AUD_USUARIO_MODIFICA = @AUD_USUARIO_MODIFICA,
	        IT.AUD_FEC_MODIFICA = GETDATE()
        FROM SGT_INTEGRANTE_TALLER IT
        WHERE ID_ESTUDIANTE = @ID_ESTUDIANTE
          AND EXISTS (
              SELECT CAST(@OBSERVACION AS varchar(MAX)),@PRONOM_ESTUDIANTE,@IND_ESTADO_INTEGRANTE,@FEC_RETIRO,@FEC_REINCORPORACION
              EXCEPT
              SELECT CAST(IT.OBSERVACION AS VARCHAR(MAX)),IT.PRONOM_ESTUDIANTE,IT.IND_ESTADO_INTEGRANTE,IT.FEC_RETIRO,IT.FEC_REINCORPORACION
          );
		IF @INICIADOR = 1 AND @@TRANCOUNT > 0
            COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT >0
			ROLLBACK TRANSACTION;
        DECLARE @ERROR NVARCHAR(4000) = ERROR_MESSAGE();
        RAISERROR (@ERROR, 16, 1);
	END CATCH
END;