USE GESTION_TALLER;

IF OBJECT_ID('AC_TALLER', 'P') IS NOT NULL
    DROP PROCEDURE AC_TALLER;
GO

CREATE PROCEDURE AC_TALLER
	@ID_TALLER INT,
	@YEAR_PROCESO INT,
	@ID_CATEGORIA INT,
	@NOMBRE_TALLER VARCHAR(80),
	@OBJETIVO_TALLER VARCHAR(500),
	@FEC_INICIO DATE,
	@FEC_TERMINO DATE,
	@NRO_MINUTOS NUMERIC(10),
	@NRO_CLASES_ANUAL NUMERIC(10),
	@HORAS_TOTALES NUMERIC(10),
	@ID_ESTADO_TALLER INT,
	@OBSERVACION VARCHAR(50),
	@LUGAR VARCHAR(100),
	@MINIMO_ESTUDIANTE INT,
	@MAXIMO_ESTUDIANTE INT,
	@REQUISITO VARCHAR(500),
	@EDAD_MINIMA INT,
	@EDAD_MAXIMA INT,
	@MATERIAL VARCHAR(500),	
	@IND_TIPO_TALLER INT,
	@AUD_USUARIO_MODIFICA VARCHAR(20)

AS BEGIN
UPDATE SGT_TALLER
SET YEAR_PROCESO=@YEAR_PROCESO,
	ID_CATEGORIA=@ID_CATEGORIA,
	NOMBRE_TALLER=@NOMBRE_TALLER,
	OBJETIVO_TALLER=@OBJETIVO_TALLER,
	FEC_INICIO=CONVERT(DATE, @FEC_INICIO, 111),
	FEC_TERMINO=CONVERT(DATE, @FEC_TERMINO, 111),
	NRO_MINUTOS=@NRO_MINUTOS,
	NRO_CLASES_ANUAL=@NRO_CLASES_ANUAL,
	HORAS_TOTALES=@HORAS_TOTALES,
	ID_ESTADO_TALLER=@ID_ESTADO_TALLER,
	FEC_ESTADO_TALLER=CASE WHEN ID_ESTADO_TALLER!=@ID_ESTADO_TALLER THEN GETDATE() ELSE FEC_ESTADO_TALLER END,
	OBSERVACION=ISNULL(@OBSERVACION, '-'),
	LUGAR=ISNULL(@LUGAR, '-'),
	MINIMO_ESTUDIANTE=@MINIMO_ESTUDIANTE,
	MAXIMO_ESTUDIANTE=@MAXIMO_ESTUDIANTE,
	REQUISITO=ISNULL(@REQUISITO, '-'),
	EDAD_MINIMA=@EDAD_MINIMA,
	EDAD_MAXIMA=@EDAD_MAXIMA,
	MATERIAL=ISNULL(@MATERIAL, '-'),
	IND_TIPO_TALLER=@IND_TIPO_TALLER,
	AUD_USUARIO_MODIFICA=@AUD_USUARIO_MODIFICA,
	AUD_FEC_MODIFICA=GETDATE()
WHERE ID_TALLER=@ID_TALLER

SELECT 'El taller a sido actualizado en el sistema' AS RESULTADO;

END;
GO