USE GESTION_TALLER;

IF OBJECT_ID('AC_ESTUDIANTE', 'P') IS NOT NULL
    DROP PROCEDURE AC_ESTUDIANTE;
GO

CREATE PROCEDURE AC_ESTUDIANTE
    @ID_ESTUDIANTE NUMERIC(10),
    @NOMBRE_PERSONA VARCHAR(50),
    @APELLIDO_PATERNO VARCHAR(50),
    @APELLIDO_MATERNO VARCHAR(50),
    @PRONOM_ESTUDIANTE VARCHAR(50),
    @GENERO INT,
    @TELEFONO VARCHAR(20),
    @CORREO_ELECTRONICO VARCHAR(100),
    @TELEFONO_CONTACTO VARCHAR(20),
    @NOMBRE_CONTACTO VARCHAR(100),
    @CORREO_CONTACTO VARCHAR(100),
    @OBSERVACION VARCHAR(500),
    @IND_ESTADO_INTEGRANTE INT,
    @ID_PAIS INT,
    @ID_COMUNA INT,
    @VILLA VARCHAR(100),
    @NRO_DPTO VARCHAR(10),
    @NRO_BLOCK VARCHAR(10),
    @NRO_CALLE VARCHAR(10),
    @CALLE VARCHAR(100),
    @FEC_INGRESO DATETIME,
    @FEC_RETIRO DATETIME,
    @FEC_REINCORPORACION DATETIME,
    @AUD_USUARIO_MODIFICA VARCHAR(20),
    @AUD_USUARIO_MODIFICA_PT VARCHAR(20),
    @AUD_USUARIO_MODIFICA_P VARCHAR(20)
AS 
BEGIN
    SET NOCOUNT ON;
    DECLARE @ID_PERSONA NUMERIC(10);

	SELECT @ID_PERSONA = ID_PERSONA FROM SGT_ESTUDIANTE WHERE ID_ESTUDIANTE = @ID_ESTUDIANTE;

	BEGIN TRY
		BEGIN TRANSACTION;

UPDATE SGT_INTEGRANTE_TALLER
SET PRONOM_ESTUDIANTE=@PRONOM_ESTUDIANTE,
	IND_ESTADO_INTEGRANTE=@IND_ESTADO_INTEGRANTE,
	FEC_RETIRO=@FEC_RETIRO,
	OBSERVACION=@OBSERVACION,
	FEC_REINCORPORACION=@FEC_REINCORPORACION,
	AUD_USUARIO_MODIFICA=@AUD_USUARIO_MODIFICA,
	AUD_FEC_MODIFICA=GETDATE()
WHERE ID_ESTUDIANTE=@ID_ESTUDIANTE 
  AND ID_TALLER=@ID_TALLER 
  AND YEAR_PROCESO=@YEAR_PROCESO;

UPDATE SGT_ESTUDIANTE;

UPDATE SGT_PERSONA_TALLER;
		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT >0
			ROLLBACK TRANSACTION;
	END CATCH
END;