USE GESTION_TALLER;

IF OBJECT_ID('AC_TALLERISTAS', 'P') IS NOT NULL
    DROP PROCEDURE AC_TALLERISTAS;
GO

CREATE PROCEDURE AC_TALLERISTAS
    @ID_PROFESOR NUMERIC(10),
    @NOMBRE_PERSONA VARCHAR(50),
    @APELLIDO_PATERNO VARCHAR(50),
    @APELLIDO_MATERNO VARCHAR(50),
    @GENERO INT,
    @TELEFONO VARCHAR(20),
    @CORREO_ELECTRONICO VARCHAR(100),
    @TELEFONO_CONTACTO VARCHAR(20),
    @NOMBRE_CONTACTO VARCHAR(100),
    @CORREO_CONTACTO VARCHAR(100),
    @PROFESION VARCHAR(500),
    @RESUMEN_CURRICULAR VARCHAR(500),
    @IND_ACTIVO BIT,
    @OBSERVACION VARCHAR(500),
    @ID_PAIS INT,
    @ID_COMUNA INT,
    @VILLA VARCHAR(100),
    @NRO_DPTO VARCHAR(10),
    @NRO_BLOCK VARCHAR(10),
    @NRO_CALLE VARCHAR(10),
    @CALLE VARCHAR(100),
    @AUD_USUARIO_MODIFICA_PT VARCHAR(20),
    @AUD_USUARIO_MODIFICA_P VARCHAR(20)
AS
BEGIN
	SET NOCOUNT ON;
    DECLARE @ID_PERSONA NUMERIC(10);

	SELECT @ID_PERSONA = ID_PERSONA FROM SGT_PROFESOR WHERE ID_PROFESOR = @ID_PROFESOR;

	BEGIN TRY
		BEGIN TRANSACTION;

		UPDATE PT
		-- SI EN ESTA TABLA SE ALTERA ALGUN DATO , FECHA DE MODIFICACION DEBERIA ACTUALIZARSE Y USUARIO TAMBIEN DEBERIA ACTUALIZARSE
		-- podria hacer eso la vrd pero por ahora lo mantendre asi , aun que no se cambie nada apenas se le de guardar esta tabla debera actualizar el tema del usuario y el tema de la fecha modifica
        SET PT.NOMBRE_PERSONA = ISNULL(@NOMBRE_PERSONA, '-'),
            PT.APELLIDO_PATERNO = ISNULL(@APELLIDO_PATERNO, '-'),
            PT.APELLIDO_MATERNO = ISNULL(@APELLIDO_MATERNO, '-'),
            PT.GENERO = CASE WHEN @GENERO IN (0,1,2,3,4) THEN @GENERO ELSE PT.GENERO END,
            PT.TELEFONO = ISNULL(@TELEFONO, '-'),
            PT.CORREO_ELECTRONICO = ISNULL(@CORREO_ELECTRONICO, '-'),
            PT.TELEFONO_CONTACTO = ISNULL(@TELEFONO_CONTACTO, '-'),
            PT.NOMBRE_CONTACTO = ISNULL(@NOMBRE_CONTACTO, '-'),
            PT.CORREO_CONTACTO = ISNULL(@CORREO_CONTACTO, '-'),
            PT.OBSERVACION = ISNULL(@OBSERVACION, '-'),
            PT.ID_PAIS = @ID_PAIS,
            PT.ID_COMUNA = @ID_COMUNA,
            PT.VILLA = ISNULL(@VILLA, '-'),
            PT.NRO_DPTO = ISNULL(@NRO_DPTO, '-'),
            PT.NRO_BLOCK = ISNULL(@NRO_BLOCK, '-'),
            PT.NRO_CALLE = ISNULL(@NRO_CALLE, '-'),
            PT.CALLE = ISNULL(@CALLE, '-'),
            PT.AUD_USUARIO_MODIFICA = CASE WHEN 
                        BINARY_CHECKSUM (PT.NOMBRE_PERSONA,PT.APELLIDO_PATERNO,PT.APELLIDO_MATERNO,PT.GENERO,PT.TELEFONO,
                            PT.CORREO_ELECTRONICO,PT.TELEFONO_CONTACTO,PT.NOMBRE_CONTACTO,PT.CORREO_CONTACTO,PT.OBSERVACION,PT.ID_PAIS,PT.ID_COMUNA,PT.VILLA,
                            PT.NRO_DPTO,PT.NRO_BLOCK,PT.NRO_CALLE,PT.CALLE) <> 
                        BINARY_CHECKSUM (@NOMBRE_PERSONA,@APELLIDO_PATERNO,@APELLIDO_MATERNO,@GENERO,@TELEFONO,@CORREO_ELECTRONICO,
                            @TELEFONO_CONTACTO,@NOMBRE_CONTACTO,@CORREO_CONTACTO,@PROFESION,@RESUMEN_CURRICULAR,@IND_ACTIVO,@OBSERVACION,
                            @ID_PAIS,@ID_COMUNA,@VILLA,@NRO_DPTO,@NRO_BLOCK,@NRO_CALLE,@CALLE) THEN @AUD_USUARIO_MODIFICA_PT ELSE PT.AUD_FEC_MODIFICA END,
            PT.AUD_FEC_MODIFICA = CASE WHEN 
                        BINARY_CHECKSUM (PT.NOMBRE_PERSONA,PT.APELLIDO_PATERNO,PT.APELLIDO_MATERNO,PT.GENERO,PT.TELEFONO,
                            PT.CORREO_ELECTRONICO,PT.TELEFONO_CONTACTO,PT.NOMBRE_CONTACTO,PT.CORREO_CONTACTO,PT.OBSERVACION,PT.ID_PAIS,PT.ID_COMUNA,PT.VILLA,
                            PT.NRO_DPTO,PT.NRO_BLOCK,PT.NRO_CALLE,PT.CALLE) <> 
                        BINARY_CHECKSUM (@NOMBRE_PERSONA,@APELLIDO_PATERNO,@APELLIDO_MATERNO,@GENERO,@TELEFONO,@CORREO_ELECTRONICO,
                            @TELEFONO_CONTACTO,@NOMBRE_CONTACTO,@CORREO_CONTACTO,@PROFESION,@RESUMEN_CURRICULAR,@IND_ACTIVO,@OBSERVACION,
                            @ID_PAIS,@ID_COMUNA,@VILLA,@NRO_DPTO,@NRO_BLOCK,@NRO_CALLE,@CALLE) THEN GETDATE() ELSE PT.AUD_FEC_MODIFICA END
        FROM SGT_PERSONA_TALLER PT
        WHERE PT.ID_PERSONA = @ID_PERSONA;

		UPDATE P
        SET P.PROFESION = @PROFESION,
            P.RESUMEN_CURRICULAR = @RESUMEN_CURRICULAR,
            P.AUD_USUARIO_MODIFICA = CASE WHEN BINARY_CHECKSUM (P.PROFESION,P.RESUMEN_CURRICULAR) <> BINARY_CHECKSUM(@PROFESION,@RESUMEN_CURRICULAR) THEN @AUD_USUARIO_MODIFICA_P END,
            P.AUD_FEC_MODIFICA = CASE WHEN BINARY_CHECKSUM (P.PROFESION,P.RESUMEN_CURRICULAR) <> BINARY_CHECKSUM(@PROFESION,@RESUMEN_CURRICULAR) THEN GETDATE() ELSE P.AUD_FEC_MODIFICA END
        FROM SGT_PROFESOR P
        WHERE P.ID_PROFESOR = @ID_PROFESOR;

		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT >0
			ROLLBACK TRANSACTION;
	END CATCH
END;
-- la base de datos es una sql server 2008 r2 , el tema es que necesito hacer un upd a 3 tablas , profesor que se conecta a administracion y este se conecta a taller