USE GESTION_TALLER;

IF OBJECT_ID('AC_TALLER', 'P') IS NOT NULL
    DROP PROCEDURE AC_TALLER;
GO

CREATE PROCEDURE AC_TALLER
	@ID_TALLER INT,
	@YEAR_PROCESO INT,
	@ID_CATEGORIA INT,
	@NOMBRE_TALLER VARCHAR(80),
	@OBJETIVO_TALLER VARCHAR(500),
	@FEC_INICIO DATE,
	@FEC_TERMINO DATE,
	@NRO_MINUTOS NUMERIC(10),
	@NRO_CLASES_ANUAL NUMERIC(10),
	@HORAS_TOTALES NUMERIC(10),
	@ID_ESTADO_TALLER INT,
	@OBSERVACION VARCHAR(50),
	@LUGAR VARCHAR(100),
	@MINIMO_ESTUDIANTE INT,
	@MAXIMO_ESTUDIANTE INT,
	@REQUISITO VARCHAR(500),
	@EDAD_MINIMA INT,
	@EDAD_MAXIMA INT,
	@MATERIAL VARCHAR(500),	
	@IND_TIPO_TALLER INT,
	@AUD_USUARIO_MODIFICA VARCHAR(20)

AS BEGIN
UPDATE T
SET T.YEAR_PROCESO=@YEAR_PROCESO,
	T.ID_CATEGORIA=@ID_CATEGORIA,
	T.NOMBRE_TALLER=@NOMBRE_TALLER,
	T.OBJETIVO_TALLER=@OBJETIVO_TALLER,
	T.FEC_INICIO=CONVERT(DATE, @FEC_INICIO, 111),
	T.FEC_TERMINO=CONVERT(DATE, @FEC_TERMINO, 111),
	T.NRO_MINUTOS=@NRO_MINUTOS,
	T.NRO_CLASES_ANUAL=@NRO_CLASES_ANUAL,
	T.HORAS_TOTALES=@HORAS_TOTALES,
	T.ID_ESTADO_TALLER=@ID_ESTADO_TALLER,
	T.FEC_ESTADO_TALLER=CASE WHEN ID_ESTADO_TALLER!=@ID_ESTADO_TALLER THEN GETDATE() ELSE FEC_ESTADO_TALLER END,
	T.OBSERVACION=ISNULL(@OBSERVACION, '-'),
	T.LUGAR=ISNULL(@LUGAR, '-'),
	T.MINIMO_ESTUDIANTE=@MINIMO_ESTUDIANTE,
	T.MAXIMO_ESTUDIANTE=@MAXIMO_ESTUDIANTE,
	T.REQUISITO=ISNULL(@REQUISITO, '-'),
	T.EDAD_MINIMA=@EDAD_MINIMA,
	T.EDAD_MAXIMA=@EDAD_MAXIMA,
	T.MATERIAL=ISNULL(@MATERIAL, '-'),
	T.IND_TIPO_TALLER=@IND_TIPO_TALLER,
	T.AUD_USUARIO_MODIFICA=@AUD_USUARIO_MODIFICA,
	T.AUD_FEC_MODIFICA=GETDATE()
FROM SGT_TALLER T
WHERE T.ID_TALLER=@ID_TALLER

--UPDATE G
--SET G.AUD_USUARIO_MODIFICA=@AUD_USUARIO_MODIFICA,
--	G.AUD_FEC_MODIFICA=GETDATE(),

--FROM SGT_GESTION_TALLER G
--WHERE G.ID_TALLER=@ID_TALLER

SELECT 'El taller a sido actualizado en el sistema' AS RESULTADO;

END;
GO