USE GESTION_TALLER;

IF OBJECT_ID('INSCRIBIRSE_ESTUDIANTE', 'P') IS NOT NULL
    DROP PROCEDURE INSCRIBIRSE_ESTUDIANTE;
GO

CREATE PROCEDURE INSCRIBIRSE_ESTUDIANTE
    --@ID_TALLER NUMERIC(10),
    --@ID_ESTUDIANTE NUMERIC(10),
    --@YEAR_PROCESO INT,
    --@IND_ESTADO_INTEGRANTE INT,
    --@FEC_INSCRIPCION DATETIME,
    --@FEC_RETIRO DATETIME,
    --@OBSERVACION TEXT,
    --@FEC_REINCORPORACION DATETIME,
    --@AUD_USUARIO_INGRESO VARCHAR(20),
    --@AUD_FEC_INGRESO DATETIME,
    --@AUD_USUARIO_MODIFICA VARCHAR(20),
    --@AUD_FEC_MODIFICA DATETIME,

	@PI_ID_TALLER				NUMERIC,
	@PI_ID_ESTUDIANTE           NUMERIC,
	@PI_IND_ESTADO_INTEGRANTE   INT,
	@PI_YEAR_PROCESO            INT,
	@PI_ID_USUARIO              VARCHAR(20)

AS
BEGIN
	SET NOCOUNT ON;
	
	DECLARE @ID_INTEGRANTE_TALLER NUMERIC,
		    @MAXIMO_ESTUDIANTE INT,
			@CANTIDAD_INSCRITO INT
	
	SELECT @MAXIMO_ESTUDIANTE = T.MAXIMO_ESTUDIANTE
	FROM SGT_TALLER T
	WHERE T.ID_TALLER = @PI_ID_TALLER
	AND T.YEAR_PROCESO = @PI_YEAR_PROCESO
		  
	SELECT @CANTIDAD_INSCRITO = COUNT(1)
	FROM SGT_INTEGRANTE_TALLER IT
	WHERE IT.ID_TALLER = @PI_ID_TALLER
	AND IT.IND_ESTADO_INTEGRANTE = 1
	AND IT.YEAR_PROCESO = @PI_YEAR_PROCESO
	
	--SELECT @CANTIDAD_INSCRITO
	
	IF ISNULL(@CANTIDAD_INSCRITO,0) >= @MAXIMO_ESTUDIANTE 
	BEGIN
		SET @PI_IND_ESTADO_INTEGRANTE = 3
	END

    INSERT INTO SGT_INTEGRANTE_TALLER
    (
		YEAR_PROCESO,
		ID_TALLER,
		ID_ESTUDIANTE,
		IND_ESTADO_INTEGRANTE,
		FEC_INSCRIPCION,
		FEC_RETIRO,
		OBSERVACION,
		FEC_REINCORPORACION,
		AUD_USUARIO_INGRESO,
		AUD_FEC_INGRESO,
		AUD_USUARIO_MODIFICA,
		AUD_FEC_MODIFICA		
    )
    
    VALUES
    (
		@PI_YEAR_PROCESO,
		@PI_ID_TALLER,
		@PI_ID_ESTUDIANTE,
		@PI_IND_ESTADO_INTEGRANTE,
		GETDATE(),
		'1900-01-01',
		'',
		'1900-01-01',
		@PI_ID_USUARIO,
		GETDATE(),
		@PI_ID_USUARIO,
		GETDATE()
    )
    
    SELECT max(ID_INTEGRANTE_TALLER)  FROM SGT_INTEGRANTE_TALLER
	WHERE ID_TALLER = @PI_ID_TALLER
	and ID_ESTUDIANTE = @PI_ID_ESTUDIANTE
	and YEAR_PROCESO = @PI_YEAR_PROCESO
    
END;