USE GESTION_TALLER;

IF OBJECT_ID('INSCRIBIRSE_ESTUDIANTE', 'P') IS NOT NULL
    DROP PROCEDURE INSCRIBIRSE_ESTUDIANTE;
GO

CREATE PROCEDURE INSCRIBIRSE_ESTUDIANTE
	@PI_RUT_ESTUDIANTE        NUMERIC,
	@PI_DV_ESTUDIANTE         CHAR(1),
	@PI_PASAPORTE			  VARCHAR(20),
	@PI_NOMBRE_ESTUDIANTE     VARCHAR(60),
	@PI_APELLIDO_PATERNO      VARCHAR(60),
	@PI_APELLIDO_MATERNO	  VARCHAR(60),
	@PI_FEC_NACIMIENTO        DATETIME,
	@PI_GENERO                INT,
	@PI_NRO_CALLE             VARCHAR(25),
	@PI_NRO_BLOCK             VARCHAR(50),
	@PI_NRO_DPTO              VARCHAR(50),
	@PI_CALLE                 VARCHAR(255),
	@PI_VILLA                 VARCHAR(50),
	@PI_ID_COMUNA		      INT,
	@PI_ID_PAIS               INT,
	@PI_TELEFONO              VARCHAR(20),
	@PI_CORREO_ELECTRONICO    VARCHAR(50),
	@PI_NOMBRE_CONTACTO       VARCHAR(50),
	@PI_TELEFONO_CONTACTO     VARCHAR(50),
	@PI_CORREO_CONTACTO       VARCHAR(255),
	@PI_OBSERVACION			  VARCHAR(50),
	@PI_ID_USUARIO            VARCHAR(20)

AS
BEGIN
	SET NOCOUNT ON;
	
	DECLARE @CANTIDAD_REGISTRO			  INT,
			@ID_ESTUDIANTE				  INT,
			@CANTIDAD_REGISTRO_ESTUDIANTE INT
	
	IF @PI_RUT_ESTUDIANTE != 0 AND @PI_PASAPORTE = ''
	BEGIN
		SELECT @CANTIDAD_REGISTRO = COUNT(1)
		FROM SGT_PERSONA_TALLER 
		WHERE RUT_PERSONA = @PI_RUT_ESTUDIANTE
	END
	ELSE

	IF @PI_RUT_ESTUDIANTE = 0 AND @PI_PASAPORTE != ''
	BEGIN
		SELECT @CANTIDAD_REGISTRO = COUNT(1)
		FROM SGT_PERSONA_TALLER
		WHERE PASAPORTE = @PI_PASAPORTE
	END
	
	IF (@PI_RUT_ESTUDIANTE IS NULL OR @PI_DV_ESTUDIANTE IS NULL OR @PI_PASAPORTE IS NULL OR @PI_DV_ESTUDIANTE = '' OR @PI_PASAPORTE = '')
    BEGIN
        RAISERROR ('Error: El RUT con DV deben estar presentes o Pasaporte debe estar presente , Como ninguna se encuentra entonces el Proceso es cancelado.', 16, 1);
        RETURN;
    END

	SET @CANTIDAD_REGISTRO = ISNULL(@CANTIDAD_REGISTRO,0)

	IF @CANTIDAD_REGISTRO = 0
	BEGIN

		INSERT INTO SGT_PERSONA_TALLER
		(
			RUT_PERSONA,
			DV_PERSONA,
			PASAPORTE,
			NOMBRE_PERSONA,
			APELLIDO_PATERNO,
			APELLIDO_MATERNO,
			FEC_NACIMIENTO,
			GENERO,
			CALLE,
			NRO_CALLE,
			NRO_BLOCK,
			NRO_DPTO,
			VILLA,
			ID_COMUNA,
			ID_PAIS,
			TELEFONO,
			CORREO_ELECTRONICO,
			NOMBRE_CONTACTO,
			TELEFONO_CONTACTO,
			CORREO_CONTACTO,
			OBSERVACION,
			AUD_USUARIO_INGRESO,
			AUD_FEC_INGRESO,
			AUD_USUARIO_MODIFICA,
			AUD_FEC_MODIFICA
		)
    
		VALUES
		(
			@PI_RUT_ESTUDIANTE,
			@PI_DV_ESTUDIANTE,
			ISNULL(@PI_PASAPORTE, ''),
			@PI_NOMBRE_ESTUDIANTE,
			@PI_APELLIDO_PATERNO,
			@PI_APELLIDO_MATERNO,
			CONVERT(DATE,@PI_FEC_NACIMIENTO, 111),
			CASE WHEN @PI_GENERO IN (0,1,2,3,4) THEN @PI_GENERO ELSE 4 END,
			@PI_CALLE,
			@PI_NRO_CALLE,
			@PI_NRO_BLOCK,
			@PI_NRO_DPTO,
			@PI_VILLA,
			@PI_ID_COMUNA,
			@PI_ID_PAIS,
			@PI_TELEFONO,
			@PI_CORREO_ELECTRONICO,
			@PI_NOMBRE_CONTACTO,
			@PI_TELEFONO_CONTACTO,
			@PI_CORREO_CONTACTO,
			@PI_OBSERVACION,
			@PI_ID_USUARIO,
			GETDATE(),
			@PI_ID_USUARIO,
			GETDATE()
		)

		DECLARE @ID_PERSONA INT = SCOPE_IDENTITY();

	END
	ELSE
	BEGIN

		SELECT @ID_PERSONA = ID_PERSONA
		FROM SGT_PERSONA_TALLER
		WHERE RUT_PERSONA = @PI_RUT_ESTUDIANTE

	END
	SET @CANTIDAD_REGISTRO_ESTUDIANTE = (SELECT COUNT(ID_ESTUDIANTE) FROM SGT_ESTUDIANTE WHERE ID_PERSONA = @ID_ESTUDIANTE)
	IF @CANTIDAD_REGISTRO_ESTUDIANTE = 0

	BEGIN
		INSERT INTO SGT_ESTUDIANTE
		(
			ID_PERSONA,
			AUD_USUARIO_INGRESO,
			AUD_FEC_INGRESO,
			AUD_USUARIO_MODIFICA,
			AUD_FEC_MODIFICA
		)
    
		VALUES
		(
			@ID_PERSONA,
			@PI_ID_USUARIO,
			GETDATE(),
			@PI_ID_USUARIO,
			GETDATE()
		);
	END

END;

--BEGIN TRY
--    BEGIN TRANSACTION
        
--        -- Tu INSERT o UPDATE aquí
--        INSERT INTO Estudiantes (Rut) VALUES (@Rut);

--        -- Validación de negocio
--        IF (@AlgunaCondicionError = 1)
--        BEGIN
--            ROLLBACK; -- Borra el insert
--            RETURN;   -- Sale del proceso
--        END

--    COMMIT TRANSACTION
--END TRY
--BEGIN CATCH
--    IF @@TRANCOUNT > 0 ROLLBACK; -- Si hubo error de SQL, deshace todo
--    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
--    RAISERROR (@ErrorMessage, 16, 1);
--END CATCH

-- 1. Buscamos si el RUT ya existe
--IF @PI_RUT_ESTUDIANTE != 0 AND @PI_PASAPORTE = ''
--BEGIN
--    SELECT @CANTIDAD_REGISTRO = COUNT(1)
--    FROM SGT_RUT
--    WHERE RUT_PERSONA = @PI_RUT_ESTUDIANTE
--END

---- 2. SI EXISTE (es decir, el conteo es mayor a 0), CANCELAMOS
--IF @CANTIDAD_REGISTRO > 0
--BEGIN
--    RAISERROR ('El proceso se cancela: El RUT ya existe en el sistema.', 16, 1);
--    RETURN; -- Esto es lo que impide que el código siga hacia abajo
--END

---- 3. Si el RUT NO existe, el código llegará aquí y hará el INSERT
--INSERT INTO TuTabla (...) 
--VALUES (...);
