USE GESTION_TALLER;

IF OBJECT_ID('INSCRIBIRSE_EN_EL_TALLER', 'P') IS NOT NULL
    DROP PROCEDURE INSCRIBIRSE_EN_EL_TALLER;
GO

CREATE PROCEDURE INSCRIBIRSE_EN_EL_TALLER
    @ID_TALLER NUMERIC(10),
    @ID_ESTUDIANTE NUMERIC(10),
    @YEAR_PROCESO INT,
    @IND_ESTADO_INTEGRANTE INT,
    @FEC_INSCRIPCION DATETIME,
    @FEC_RETIRO DATETIME,
    @OBSERVACION TEXT,
    @FEC_REINCORPORACION DATETIME,
    @AUD_USUARIO_INGRESO VARCHAR(20),
    @AUD_FEC_INGRESO DATETIME,
    @AUD_USUARIO_MODIFICA VARCHAR(20),
    @AUD_FEC_MODIFICA DATETIME

AS BEGIN
INSERT INTO SGT_INTEGRANTE_TALLER (
    ID_TALLER, 
    ID_ESTUDIANTE, 
    YEAR_PROCESO, 
    IND_ESTADO_INTEGRANTE, 
    FEC_INSCRIPCION, 
    FEC_RETIRO, 
    OBSERVACION,
    FEC_REINCORPORACION, 
    AUD_USUARIO_INGRESO, 
    AUD_FEC_INGRESO, 
    AUD_USUARIO_MODIFICA, 
    AUD_FEC_MODIFICA)
VALUES (
    @ID_TALLER,
    @ID_ESTUDIANTE,
    @YEAR_PROCESO,
    1,
    GETDATE(),
    '1900-01-01 00:00:00.000',
    '-',
    '1900-01-01 00:00:00.000',
    @AUD_USUARIO_INGRESO,
    GETDATE(),
    'SISTEMA',
    '1900-01-01 00:00:00.000'
);

SELECT 'Los datos se han ingresado al sistema' AS RESULTADO;

END;