USE GESTION_TALLER;

IF OBJECT_ID('INSCRIBIR_TALLERISTAS', 'P') IS NOT NULL
    DROP PROCEDURE INSCRIBIR_TALLERISTAS;
GO

CREATE PROCEDURE INSCRIBIR_TALLERISTAS --falta actualizar, pero no es prioridad hasta tener primero lo de estudiante terminado
@ID_PERSONA NUMERIC(10),
@PROFESION VARCHAR(250),
@RESUMEN_CURRICULAR VARCHAR(250),
@AUD_USUARIO_INGRESO VARCHAR(250)

AS BEGIN
SET NOCOUNT ON;
INSERT INTO SGT_PROFESOR (
    ID_PERSONA, 
    PROFESION, 
    RESUMEN_CURRICULAR, 
    AUD_USUARIO_INGRESO, 
    AUD_FEC_INGRESO, 
    AUD_USUARIO_MODIFICA, 
    AUD_FEC_MODIFICA)
VALUES (
    @ID_PERSONA,
    COALESCE(NULLIF(@PROFESION, ''), '-'),  
    COALESCE(NULLIF(@RESUMEN_CURRICULAR, ''), '-'),
    COALESCE(NULLIF(@AUD_USUARIO_INGRESO, ''), 'SISTEMA'),
    GETDATE(),
    'SISTEMA',
    '1900-01-01 00:00:00.000'
    );

SELECT 'Se ingreso datos de "Profesor/a" al sistema' AS RESULTADO;

END;