USE GESTION_TALLER;

IF OBJECT_ID('INSCRIBIR_TALLERISTAS', 'P') IS NOT NULL
    DROP PROCEDURE INSCRIBIR_TALLERISTAS;
GO

CREATE PROCEDURE INSCRIBIR_TALLERISTAS
	@PI_RUT_PROFESOR          NUMERIC(10),
	@PI_DV_PROFESOR           CHAR(1),
	@PI_PASAPORTE			  VARCHAR(20),
	@PI_NOMBRE_PROFESOR       VARCHAR(60),
	@PI_APELLIDO_PATERNO      VARCHAR(60),
	@PI_APELLIDO_MATERNO      VARCHAR(60),
	@PI_FEC_NACIMIENTO	      DATETIME,
	@PI_GENERO                INT,
	@PI_NRO_CALLE             VARCHAR(25),
	@PI_NRO_BLOCK             VARCHAR(50),
	@PI_NRO_DPTO              VARCHAR(50),
	@PI_CALLE                 VARCHAR(255),
	@PI_VILLA                 VARCHAR(50),
	@PI_ID_COMUNA             INT,
	@PI_ID_PAIS		          INT,
	@PI_TELEFONO		      VARCHAR(20),
	@PI_CORREO_ELECTRONICO    VARCHAR(50),
	@PI_NOMBRE_CONTACTO       VARCHAR(255),
	@PI_TELEFONO_CONTACTO     VARCHAR(25),
	@PI_CORREO_CONTACTO       VARCHAR(255),
	@PI_OBSERVACION           VARCHAR(255),
	@PI_ID_USUARIO            VARCHAR(20),
	@PI_PROFESION             VARCHAR(50),
	@PI_RESUMEN_CURRICULAR    VARCHAR(500)
AS
BEGIN

	SET NOCOUNT ON;

	DECLARE @CANTIDAD_REGISTRO INT,
			@ID_PROFESOR INT,
			@CANTIDAD_REGISTRO_PROFESOR INT

	IF @PI_RUT_PROFESOR != 0 AND @PI_PASAPORTE = ''
	BEGIN
		SELECT @CANTIDAD_REGISTRO = COUNT(1)
		FROM SGT_PERSONA_TALLER
		WHERE RUT_PERSONA = @PI_RUT_PROFESOR
	END
	ELSE

	IF @PI_RUT_PROFESOR = 0 AND @PI_PASAPORTE != ''
	BEGIN
		SELECT @CANTIDAD_REGISTRO = COUNT(1)
		FROM SGT_PERSONA_TALLER
		WHERE PASAPORTE = @PI_PASAPORTE
	END

	IF (@PI_RUT_PROFESOR IS NULL OR @PI_DV_PROFESOR IS NULL OR @PI_PASAPORTE IS NULL OR @PI_DV_PROFESOR = '' OR @PI_PASAPORTE = '')
	BEGIN
		RAISERROR ('Error: El RUT con DV deben estar presentes o Pasaporte debe estar presente , Como ninguna se encuentra entonces el Proceso es cancelado.', 16, 1);
        RETURN;
	END

	SET @CANTIDAD_REGISTRO = ISNULL(@CANTIDAD_REGISTRO,0)

	IF @CANTIDAD_REGISTRO = 0
	BEGIN

		INSERT INTO SGT_PERSONA_TALLER
		(
			RUT_PERSONA,
			DV_PERSONA,
			PASAPORTE,
			NOMBRE_PERSONA,
			APELLIDO_PATERNO,
			APELLIDO_MATERNO,
			FEC_NACIMIENTO,
			GENERO,
			CALLE,
			NRO_CALLE,
			NRO_BLOCK,
			NRO_DPTO,
			VILLA,
			ID_COMUNA,
			ID_PAIS,
			TELEFONO,
			CORREO_ELECTRONICO,
			NOMBRE_CONTACTO,
			TELEFONO_CONTACTO,
			CORREO_CONTACTO,
			OBSERVACION,
			AUD_USUARIO_INGRESO,
			AUD_FEC_INGRESO,
			AUD_USUARIO_MODIFICA,
			AUD_FEC_MODIFICA
		)
	
		VALUES
		(
			@PI_RUT_PROFESOR,
			@PI_DV_PROFESOR,
			ISNULL(@PI_PASAPORTE, ''),
			@PI_NOMBRE_PROFESOR,
			@PI_APELLIDO_PATERNO,
			@PI_APELLIDO_MATERNO,
			CONVERT(DATE,@PI_FEC_NACIMIENTO, 111),
			CASE WHEN @PI_GENERO IN (0,1,2,3,4) THEN @PI_GENERO ELSE 4 END,
			@PI_CALLE,
			@PI_NRO_CALLE,
			@PI_NRO_BLOCK,
			@PI_NRO_DPTO,
			@PI_VILLA,
			@PI_ID_COMUNA,
			@PI_ID_PAIS,
			@PI_TELEFONO,
			@PI_CORREO_ELECTRONICO,
			@PI_NOMBRE_CONTACTO,
			@PI_TELEFONO_CONTACTO,
			@PI_CORREO_CONTACTO,
			@PI_OBSERVACION,
			@PI_ID_USUARIO,
			GETDATE(),
			@PI_ID_USUARIO,
			GETDATE()
		)
	
		DECLARE @ID_PERSONA INT = SCOPE_IDENTITY();

	END
	ELSE
	BEGIN
	
		SELECT @ID_PERSONA = ID_PERSONA
		FROM SGT_PERSONA_TALLER
		WHERE RUT_PERSONA = @PI_RUT_PROFESOR

	END	
	SET @CANTIDAD_REGISTRO_PROFESOR = (SELECT COUNT(ID_PROFESOR) FROM SGT_PROFESOR WHERE ID_PERSONA = @ID_PROFESOR)
	IF @CANTIDAD_REGISTRO_PROFESOR = 0
		BEGIN
			INSERT INTO SGT_PROFESOR
			(
				ID_PERSONA,
				PROFESION,
				RESUMEN_CURRICULAR,
				AUD_USUARIO_INGRESO,
				AUD_FEC_INGRESO,
				AUD_USUARIO_MODIFICA,
				AUD_FEC_MODIFICA
			)
    
			VALUES
			(
				@ID_PERSONA,
				@PI_PROFESION,
				@PI_RESUMEN_CURRICULAR,
				@PI_ID_USUARIO,
				GETDATE(),
				@PI_ID_USUARIO,
				GETDATE()
			);
		END
END;