USE GESTION_TALLER;

IF OBJECT_ID('INSCRIBIR_EL_TALLER', 'P') IS NOT NULL
    DROP PROCEDURE INSCRIBIR_EL_TALLER;
GO
-- SE TIENE QUE MEJORAR, SI ESTO PUEDA TENER LA OPCION DE METER MULTIPLES TALELRISTAS ESTARIA BUENO
CREATE PROCEDURE INSCRIBIR_EL_TALLER
    @ID_PROFESOR NUMERIC(10),
    @YEAR_PROCESO INT,
    @ID_CATEGORIA INT,
    @NOMBRE_TALLER VARCHAR(80),
    @OBJETIVO_TALLER VARCHAR(500),
    @FEC_INICIO DATE,
    @FEC_TERMINO DATE,
    @NRO_MINUTOS NUMERIC(10),
    @NRO_CLASES_ANUAL NUMERIC(10),
    @HORAS_TOTALES NUMERIC(10),
    @ID_ESTADO_TALLER INT,
    @OBSERVACION VARCHAR(50),
    @LUGAR VARCHAR(100),
    @MINIMO_ESTUDIANTE INT,
    @MAXIMO_ESTUDIANTE INT,
    @REQUISITO VARCHAR(500),
    @EDAD_MINIMA INT,
    @EDAD_MAXIMA INT,
    @MATERIAL VARCHAR(500),
    @IND_TIPO_TALLER INT,
    @AUD_USUARIO_INGRESO VARCHAR(20)

AS 
BEGIN
SET NOCOUNT ON;

    DECLARE @ID_TALLER NUMERIC

    INSERT INTO SGT_TALLER 
        (YEAR_PROCESO,
        ID_CATEGORIA,
        NOMBRE_TALLER,
        ID_DEPARTAMENTO,
        OBJETIVO_TALLER,
        FEC_INICIO,
        FEC_TERMINO,
        NRO_MINUTOS,
        NRO_CLASES_ANUAL,
        HORAS_TOTALES,
        ID_ESTADO_TALLER,
        FEC_ESTADO_TALLER,
        OBSERVACION,
        LUGAR,
        MINIMO_ESTUDIANTE,
        MAXIMO_ESTUDIANTE,
        REQUISITO,
        EDAD_MINIMA,
        EDAD_MAXIMA,
        MATERIAL,
        IND_TIPO_TALLER,
        AUD_USUARIO_INGRESO,
        AUD_FEC_INGRESO,
        AUD_USUARIO_MODIFICA,
        AUD_FEC_MODIFICA)

    VALUES (@YEAR_PROCESO,@ID_CATEGORIA,@NOMBRE_TALLER,
        169,
        COALESCE(NULLIF(@OBJETIVO_TALLER, ''), '-'),
        @FEC_INICIO,
        @FEC_TERMINO,
        @NRO_MINUTOS,
        @NRO_CLASES_ANUAL,
        @HORAS_TOTALES,
        CASE WHEN @ID_ESTADO_TALLER IN (1, 2, 3, 4) THEN @ID_ESTADO_TALLER ELSE 4 END,
        GETDATE(),
        COALESCE(NULLIF(@OBSERVACION, ''), '-'),
        COALESCE(NULLIF(@LUGAR, ''), '-'),
        @MINIMO_ESTUDIANTE,
        @MAXIMO_ESTUDIANTE,
        COALESCE(NULLIF(@REQUISITO, ''), '-'),
        @EDAD_MINIMA,
        @EDAD_MAXIMA,
        COALESCE(NULLIF(@MATERIAL, ''), '-'),
        CASE WHEN @IND_TIPO_TALLER IN (1,2) THEN @IND_TIPO_TALLER ELSE 0 END,
        COALESCE(NULLIF(@AUD_USUARIO_INGRESO, ''), 'SISTEMA'),
        GETDATE(),
        COALESCE(NULLIF(@AUD_USUARIO_INGRESO, ''), 'SISTEMA'),
        GETDATE())

    SET @ID_TALLER = @@IDENTITY

    INSERT INTO SGT_GESTION_TALLER
        (ID_TALLER,
        ID_PROFESOR,
        YEAR_PROCESO,
        AUD_USUARIO_INGRESO,
        AUD_FEC_INGRESO,
        AUD_USUARIO_MODIFICA,
        AUD_FEC_MODIFICA)

    VALUES (@ID_TALLER,
        @ID_PROFESOR,
        @YEAR_PROCESO,
        @AUD_USUARIO_INGRESO,
        GETDATE(),
        @AUD_USUARIO_INGRESO,
        GETDATE());

SELECT 'El taller a sido ingresado al sistema' AS RESULTADO;

END;