USE GESTION_TALLER;

IF OBJECT_ID('INSCRIBIR_TALLERISTAS', 'P') IS NOT NULL
    DROP PROCEDURE INSCRIBIR_TALLERISTAS;
GO

CREATE PROCEDURE INSCRIBIR_TALLERISTAS
	@PI_RUT_PROFESOR          NUMERIC,
	@PI_DV_PROFESOR           CHAR(1),
	@PI_NOMBRE_PROFESOR       VARCHAR(60),
	@PI_APELLIDO_PATERNO      VARCHAR(60),
	@PI_APELLIDO_MATERNO      VARCHAR(60),
	@PI_FEC_NACIMIENTO	      DATETIME,
	--@PI_EDAD			      INT,
	@PI_GENERO                INT,
	@PI_NRO_CALLE             VARCHAR(25),
	@PI_NRO_BLOCK             VARCHAR(50),
	@PI_NRO_DPTO              VARCHAR(50),
	@PI_CALLE                 VARCHAR(255),
	@PI_VILLA                 VARCHAR(50),
	@PI_ID_COMUNA             INT,
	@PI_ID_PAIS		          INT,
	@PI_TELEFONO		      VARCHAR(20),
	@PI_CORREO_ELECTRONICO    VARCHAR(50),
	@PI_NOMBRE_CONTACTO       VARCHAR(255),
	@PI_TELEFONO_CONTACTO     VARCHAR(25),
	@PI_CORREO_CONTACTO       VARCHAR(255),
	@PI_OBSERVACION           VARCHAR(255),
	@PI_ID_USUARIO            VARCHAR(20),
	@PI_PROFESION             VARCHAR(50),
	@PI_RESUMEN_CURRICULAR    VARCHAR(500)
AS
BEGIN

	SET NOCOUNT ON;

	DECLARE @ID_PERSONA NUMERIC

	INSERT INTO SGT_PERSONA_TALLER
	(
		RUT_PERSONA,
		DV_PERSONA,
		NOMBRE_PERSONA,
		APELLIDO_PATERNO,
		APELLIDO_MATERNO,
		FEC_NACIMIENTO,
		--EDAD,
		GENERO,
		CALLE,
		NRO_CALLE,
		NRO_BLOCK,
		NRO_DPTO,
		VILLA,
		ID_COMUNA,
		ID_PAIS,
		TELEFONO,
		CORREO_ELECTRONICO,
		NOMBRE_CONTACTO,
		TELEFONO_CONTACTO,
		CORREO_CONTACTO,
		OBSERVACION,
		IND_ACTIVO,
		AUD_USUARIO_INGRESO,
		AUD_FEC_INGRESO,
		AUD_USUARIO_MODIFICA,
		AUD_FEC_MODIFICA
	)
	
	VALUES
	(
		@PI_RUT_PROFESOR,
		@PI_DV_PROFESOR,
		@PI_NOMBRE_PROFESOR,
		@PI_APELLIDO_PATERNO,
		@PI_APELLIDO_MATERNO,
		@PI_FEC_NACIMIENTO,
		--@PI_EDAD,
		@PI_GENERO,
		@PI_CALLE,
		@PI_NRO_CALLE,
		@PI_NRO_BLOCK,
		@PI_NRO_DPTO,
		@PI_VILLA,
		@PI_ID_COMUNA,
		@PI_ID_PAIS,
		@PI_TELEFONO,
		@PI_CORREO_ELECTRONICO,
		@PI_NOMBRE_CONTACTO,
		@PI_TELEFONO_CONTACTO,
		@PI_CORREO_CONTACTO,
		@PI_OBSERVACION,
		1,
		@PI_ID_USUARIO,
		GETDATE(),
		'SISTEMA',
		'1900-01-01 00:00:00.000'
	)
	
	SET @ID_PERSONA = @@IDENTITY

    INSERT INTO SGT_PROFESOR
    (
		ID_PERSONA,
		PROFESION,
		RESUMEN_CURRICULAR,
		AUD_USUARIO_INGRESO,
		AUD_FEC_INGRESO,
		AUD_USUARIO_MODIFICA,
		AUD_FEC_MODIFICA
    )
    
    VALUES
    (
		@ID_PERSONA,
		@PI_PROFESION,
		@PI_RESUMEN_CURRICULAR,
		@PI_ID_USUARIO,
		GETDATE(),
		'SISTEMA',
		'1900-01-01 00:00:00.000'
    )
END
GO