USE GESTION_TALLER;

IF OBJECT_ID('INSCRIBIR_EL_TALLER', 'P') IS NOT NULL
    DROP PROCEDURE INSCRIBIR_EL_TALLER;
GO
CREATE PROCEDURE INSCRIBIR_EL_TALLER
    @YEAR_PROCESO INT,
    @ID_CATEGORIA INT,
    @NOMBRE_TALLER VARCHAR(80),
    @OBJETIVO_TALLER VARCHAR(500),
    @FEC_INICIO DATE,
    @FEC_TERMINO DATE,
    @NRO_MINUTOS NUMERIC(10),
    @NRO_CLASES_ANUAL NUMERIC(10),
    @HORAS_TOTALES NUMERIC(10),
    @ID_ESTADO_TALLER INT,
    @OBSERVACION VARCHAR(50),
    @LUGAR VARCHAR(100),
    @MINIMO_ESTUDIANTE INT,
    @MAXIMO_ESTUDIANTE INT,
    @REQUISITO VARCHAR(500),
    @EDAD_MINIMA INT,
    @EDAD_MAXIMA INT,
    @MATERIAL VARCHAR(500),
    @IND_TIPO_TALLER INT,
    @AUD_USUARIO_INGRESO VARCHAR(20),
    @ID_TALLER_OUTPUT INT OUTPUT

AS 
BEGIN
SET NOCOUNT ON;
--SET IDENTITY_INSERT SGT_TALLER ON;
    INSERT INTO SGT_TALLER 
        (YEAR_PROCESO,
        ID_CATEGORIA,
        NOMBRE_TALLER,
        ID_DEPARTAMENTO,
        OBJETIVO_TALLER,
        FEC_INICIO,
        FEC_TERMINO,
        NRO_MINUTOS,
        NRO_CLASES_ANUAL,
        HORAS_TOTALES,
        ID_ESTADO_TALLER,
        FEC_ESTADO_TALLER,
        OBSERVACION,
        LUGAR,
        MINIMO_ESTUDIANTE,
        MAXIMO_ESTUDIANTE,
        REQUISITO,
        EDAD_MINIMA,
        EDAD_MAXIMA,
        MATERIAL,
        IND_TIPO_TALLER,
        AUD_USUARIO_INGRESO,
        AUD_FEC_INGRESO,
        AUD_USUARIO_MODIFICA,
        AUD_FEC_MODIFICA)

    VALUES (@YEAR_PROCESO,@ID_CATEGORIA,@NOMBRE_TALLER,
        169,
        ISNULL(@OBJETIVO_TALLER, '-'),
        NULLIF(@FEC_INICIO, '1900-01-01'),
	    NULLIF(@FEC_TERMINO, '1900-01-01'),
        ISNULL(@NRO_MINUTOS, 0),
        ISNULL(@NRO_CLASES_ANUAL, 0),
        ISNULL(@HORAS_TOTALES, 0),
        ISNULL(@ID_ESTADO_TALLER, 2),
        GETDATE(),
        ISNULL(@OBSERVACION, '-'),
        ISNULL(@LUGAR, '-'),
        ISNULL(@MINIMO_ESTUDIANTE, 0),
        ISNULL(@MAXIMO_ESTUDIANTE, 0),
        ISNULL(@REQUISITO, '-'),
        ISNULL(@EDAD_MINIMA, 18),
        ISNULL(@EDAD_MAXIMA, 18),
        ISNULL(@MATERIAL, '-'),
        @IND_TIPO_TALLER,
        ISNULL(@AUD_USUARIO_INGRESO, 'SISTEMA'),
        GETDATE(),
        'SISTEMA',
        CONVERT(DATE, '1900-01-01 00:00:00.000', 121)
    );
    SET @ID_TALLER_OUTPUT = SCOPE_IDENTITY();

SELECT 'El taller a sido ingresado al sistema' AS RESULTADO;

END;