USE [GESTION_TALLER]
GO

/****** Object:  Table [dbo].[SGT_DOCUMENTO_ESTUDIANTE]    Script Date: 30/04/2026 04:27:06 p. m. ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SGT_DOCUMENTO_ESTUDIANTE]') AND type in (N'U'))
DROP TABLE [dbo].[SGT_DOCUMENTO_ESTUDIANTE]
GO

/****** Object:  Table [dbo].[SGT_DOCUMENTO_ESTUDIANTE]    Script Date: 30/04/2026 04:27:06 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SGT_DOCUMENTO_ESTUDIANTE](
	[ID_DOCUMENTO_ESTUDIANTE] [int] NOT NULL,
	[ID_ESTUDIANTE] [numeric](10, 0) NOT NULL,
	[NOMBRE_DOCUMENTO] [varchar](max) NOT NULL,
	[ID_TIPO_DOCUMENTO] [int] NOT NULL,
	[ID_TALLER] [int] NULL,
	[AUD_FECHA_INGRESO] [datetime] NOT NULL,
	[AUD_USUARIO_INGRESO] [varchar](60) NOT NULL,
	[AUD_FECHA_MODIFICA] [datetime] NOT NULL,
	[AUD_USUARIO_MODIFICA] [varchar](60) NOT NULL,
 CONSTRAINT [PK__SGT_DOCU__94C6D7377948ECA7] PRIMARY KEY CLUSTERED 
(
	[ID_DOCUMENTO_ESTUDIANTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


