USE [GESTION_TALLER]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] DROP CONSTRAINT [DF__SGT_PERSO__AUD_F__5B837F96]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] DROP CONSTRAINT [DF__SGT_PERSO__AUD_U__5A8F5B5D]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] DROP CONSTRAINT [DF__SGT_PERSO__INTEN__599B3724]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] DROP CONSTRAINT [DF__SGT_PERSO__ULTIM__58A712EB]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] DROP CONSTRAINT [DF__SGT_PERSO__FEC_C__57B2EEB2]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] DROP CONSTRAINT [DF__SGT_PERSO__IND_A__56BECA79]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] DROP CONSTRAINT [DF__SGT_PERSO__TIPO___55CAA640]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SGT_PERSONA_TALLER]') AND type in (N'U'))
DROP TABLE [dbo].[SGT_PERSONA_TALLER]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SGT_PERSONA_TALLER](
	[ID_PERSONA] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
	[RUT_PERSONA] [numeric](10, 0) NULL,
	[DV_PERSONA] [char](1) NULL,
	[PASAPORTE] [varchar](30) NULL,
	[NOMBRE_PERSONA] [varchar](50) NOT NULL,
	[APELLIDO_PATERNO] [varchar](50) NOT NULL,
	[APELLIDO_MATERNO] [varchar](50) NOT NULL,
	[FEC_NACIMIENTO] [date] NOT NULL,
	[EDAD] [int] NULL,
	[GENERO] [char](1) NULL,
	[TELEFONO] [varchar](20) NOT NULL,
	[CORREO_ELECTRONICO] [varchar](100) NOT NULL,
	[CALLE] [varchar](100) NOT NULL,
	[NRO_CALLE] [varchar](10) NULL,
	[NRO_BLOCK] [varchar](10) NULL,
	[NRO_DPTO] [varchar](10) NULL,
	[VILLA] [varchar](100) NULL,
	[ID_COMUNA] [int] NOT NULL,
	[ID_PAIS] [int] NOT NULL,
	[TELEFONO_CONTACTO] [varchar](20) NULL,
	[NOMBRE_CONTACTO] [varchar](100) NULL,
	[CORREO_CONTACTO] [varchar](100) NULL,
	[OBSERVACION] [varchar](500) NULL,
	[CONTRASENA_HASH] [varchar](255) NOT NULL,
	[TIPO_USUARIO] [varchar](20) NOT NULL,
	[IND_ACTIVO] [bit] NOT NULL,
	[FEC_CREACION] [datetime] NULL,
	[ULTIMO_ACCESO] [datetime] NULL,
	[INTENTOS_FALLIDOS] [int] NULL,
	[BLOQUEADO_HASTA] [datetime] NULL,
	[AUD_USUARIO_INGRESO] [varchar](20) NULL,
	[AUD_FEC_INGRESO] [datetime] NULL,
	[AUD_FEC_MODIFICA] [datetime] NULL,
	[AUD_USUARIO_MODIFICA] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_PERSONA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ('FUNCIONARIO') FOR [TIPO_USUARIO]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ((1)) FOR [IND_ACTIVO]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT (getdate()) FOR [FEC_CREACION]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT (getdate()) FOR [ULTIMO_ACCESO]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ((0)) FOR [INTENTOS_FALLIDOS]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ('SISTEMA') FOR [AUD_USUARIO_INGRESO]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT (getdate()) FOR [AUD_FEC_INGRESO]
GO


