USE GESTION_TALLER;

IF OBJECT_ID('SGT_LISTA_ESPERA', 'U') IS NOT NULL
    DROP TABLE SGT_LISTA_ESPERA;
GO

CREATE TABLE SGT_LISTA_ESPERA(
    ID_ESPERA NUMERIC IDENTITY(1,1) PRIMARY KEY NOT NULL,
    ID_TALLER NUMERIC(10,0) NOT NULL,
    ID_ESTUDIANTE NUMERIC(10,0) NOT NULL,
    YEAR_PROCESO INT NOT NULL,
    IND_ESTADO_INTEGRANTE INT NOT NULL,
    FECHA_ESPERA DATETIME NOT NULL DEFAULT GETDATE(),
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'En Espera',
    
    CONSTRAINT FK_LISTA_ESPERA_SGT_TALLER
        FOREIGN KEY (ID_TALLER)
        REFERENCES SGT_TALLER(ID_TALLER),

    CONSTRAINT FK_LISTA_ESPERA_SGT_ESTUDIANTE
        FOREIGN KEY (ID_ESTUDIANTE)
        REFERENCES SGT_ESTUDIANTE(ID_ESTUDIANTE)
);
GO