USE [GESTION_TALLER]
GO

/****** Object:  Table [dbo].[SGT_PERSONA_FUNCIONARIO]    Script Date: 23/04/2026 10:03:08 a. m. ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SGT_PERSONA_FUNCIONARIO]') AND type in (N'U'))
DROP TABLE [dbo].[SGT_PERSONA_FUNCIONARIO]
GO

/****** Object:  Table [dbo].[SGT_PERSONA_FUNCIONARIO]    Script Date: 23/04/2026 10:03:08 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SGT_PERSONA_FUNCIONARIO](
	[ID_F] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
	[RUT_F] [numeric](10, 0) NOT NULL,
	[DV_F] [char](1) NOT NULL,
	[NOMBRE_F] [varchar](60) NOT NULL,
	[APELLIDO_PATERNO_F] [varchar](60) NOT NULL,
	[APELLIDO_MATERNO_F] [varchar](60) NOT NULL,
	[FEC_NACIMIENTO_F] [datetime] NOT NULL,
	[EDAD_F] [int] NOT NULL,
	[GENERO_F] [int] NOT NULL,
	[NRO_CALLE_F] [varchar](25) NULL,
	[NRO_BLOCK_F] [varchar](50) NULL,
	[NRO_DPTO_F] [varchar](50) NULL,
	[CALLE_F] [varchar](255) NOT NULL,
	[VILLA_F] [varchar](50) NULL,
	[ID_PAIS_F] [int] NOT NULL,
	[ID_COMUNA_F] [int] NOT NULL,
	[TELEFONO_F] [varchar](20) NOT NULL,
	[CORREO_ELECTRONICO_F] [varchar](50) NOT NULL,
	[NOMBRE_CONTACTO_F] [varchar](255) NOT NULL,
	[TELEFONO_CONTACTO_F] [varchar](25) NOT NULL,
	[CORREO_CONTACTO_F] [varchar](255) NOT NULL,
	[OBSERVACION_F] [varchar](255) NULL,
	[ID_USUARIO_F] [varchar](20) NOT NULL,
	[PASSWORD_F] [varchar](20) NOT NULL,
 CONSTRAINT [PK_SGT_PERSONA_FUNCIONARIO] PRIMARY KEY CLUSTERED 
(
	[ID_F] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


