USE [GESTION_TALLER]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] DROP CONSTRAINT [DF__SGT_PERSO__AUD_F__5B837F96]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] DROP CONSTRAINT [DF__SGT_PERSO__AUD_U__5A8F5B5D]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] DROP CONSTRAINT [DF__SGT_PERSO__INTEN__599B3724]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] DROP CONSTRAINT [DF__SGT_PERSO__ULTIM__58A712EB]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] DROP CONSTRAINT [DF__SGT_PERSO__FEC_C__57B2EEB2]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] DROP CONSTRAINT [DF__SGT_PERSO__IND_A__56BECA79]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] DROP CONSTRAINT [DF__SGT_PERSO__TIPO___55CAA640]
GO

/****** Object:  Table [dbo].[SGT_PERSONA_TALLER]    Script Date: 23/04/2026 03:09:11 p. m. ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SGT_PERSONA_TALLER]') AND type in (N'U'))
DROP TABLE [dbo].[SGT_PERSONA_TALLER]
GO

/****** Object:  Table [dbo].[SGT_PERSONA_TALLER]    Script Date: 23/04/2026 03:09:11 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SGT_PERSONA_TALLER](
	[ID_PERSONA] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
	[RUT_PERSONA] [numeric](10, 0) NULL,
	[DV_PERSONA] [char](1) NULL,
	[PASAPORTE] [varchar](20) NULL,
	[NOMBRE_PERSONA] [varchar](60) NOT NULL,
	[APELLIDO_PATERNO] [varchar](60) NOT NULL,
	[APELLIDO_MATERNO] [varchar](60) NOT NULL,
	[FEC_NACIMIENTO] [datetime] NOT NULL,
	[EDAD] [int] NOT NULL,
	[GENERO] [int] NOT NULL,
	[TELEFONO] [varchar](20) NOT NULL,
	[CORREO_ELECTRONICO] [varchar](50) NOT NULL,
	[CALLE] [varchar](255) NOT NULL,
	[NRO_CALLE] [varchar](25) NOT NULL,
	[NRO_BLOCK] [varchar](50) NULL,
	[NRO_DPTO] [varchar](50) NULL,
	[VILLA] [varchar](50) NULL,
	[ID_COMUNA] [int] NOT NULL,
	[ID_PAIS] [int] NOT NULL,
	[TELEFONO_CONTACTO] [varchar](20) NOT NULL,
	[NOMBRE_CONTACTO] [varchar](183) NOT NULL,
	[CORREO_CONTACTO] [varchar](50) NOT NULL,
	[OBSERVACION] [varchar](255) NOT NULL,
	[CONTRASENA_HASH] [varchar](255) NOT NULL,
	[TIPO_USUARIO] [varchar](20) NOT NULL,
	[IND_ACTIVO] [bit] NOT NULL,
	[AUD_USUARIO_INGRESO] [varchar](20) NOT NULL,
	[AUD_FEC_INGRESO] [datetime] NOT NULL,
	[AUD_USUARIO_MODIFICA] [varchar](20) NOT NULL,
	[AUD_FEC_MODIFICA] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_PERSONA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ((0)) FOR [RUT_PERSONA]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ('-') FOR [DV_PERSONA]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ('-') FOR [PASAPORTE]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ((0)) FOR [EDAD]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ((0)) FOR [GENERO]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ('-') FOR [CALLE]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ('-') FOR [NRO_CALLE]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ('-') FOR [NRO_BLOCK]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ('-') FOR [NRO_DPTO]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ('-') FOR [VILLA]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ('-') FOR [TELEFONO_CONTACTO]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ('-') FOR [NOMBRE_CONTACTO]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ('-') FOR [CORREO_CONTACTO]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ('-') FOR [OBSERVACION]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ('123123123') FOR [CONTRASENA_HASH]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ('ESTUDIANTE') FOR [TIPO_USUARIO]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ((1)) FOR [IND_ACTIVO]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ('SISTEMA') FOR [AUD_USUARIO_INGRESO]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT (GETDATE()) FOR [AUD_FEC_INGRESO]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ('SISTEMA') FOR [AUD_USUARIO_MODIFICA]
GO

ALTER TABLE [dbo].[SGT_PERSONA_TALLER] ADD  DEFAULT ('1900-01-01 00:00:00.000') FOR [AUD_FEC_MODIFICA]
GO
