USE GESTION_TALLER;

IF OBJECT_ID('SGT_PERSONA_TALLER', 'U') IS NOT NULL
    DROP TABLE SGT_PERSONA_TALLER;
GO

CREATE TABLE SGT_PERSONA_TALLER(
    ID_PERSONA NUMERIC (10,0) IDENTITY PRIMARY KEY NOT NULL,
    RUT_PERSONA NUMERIC (10,0),
    DV_PERSONA CHAR (1),
    PASAPORTE VARCHAR (30),
    NOMBRE_PERSONA VARCHAR (50) NOT NULL,
    APELLIDO_PATERNO VARCHAR (50) NOT NULL,
    APELLIDO_MATERNO VARCHAR (50) NOT NULL,
    FEC_NACIMIENTO DATE NOT NULL,
    EDAD INT,
    GENERO CHAR (1),
    TELEFONO VARCHAR (20) NOT NULL,
    CORREO_ELECTRONICO VARCHAR (100) NOT NULL,
    CALLE VARCHAR (100) NOT NULL,
    NRO_CALLE VARCHAR (10),
    NRO_BLOCK VARCHAR (10),
    NRO_DPTO VARCHAR (10),
    VILLA VARCHAR (100),
    ID_COMUNA INT NOT NULL,
    ID_PAIS INT NOT NULL,
    TELEFONO_CONTACTO VARCHAR (20),
    NOMBRE_CONTACTO VARCHAR (100),
    CORREO_CONTACTO VARCHAR (100),
    OBSERVACION VARCHAR (500),
    CONTRASENA_HASH VARCHAR (255) NOT NULL,
    TIPO_USUARIO VARCHAR (20) NOT NULL DEFAULT 'FUNCIONARIO', 
    --los tipos de usuario son 'FUNCIONARIO' o 'ADMIN', en el caso de que sea alguien de algun taller ya sea profesor o estudiante se le dejara como 'ESTUDIANTE' o 'PROFESOR' ya que no es un usuario
    IND_ACTIVO BIT NOT NULL DEFAULT 1,
    FEC_CREACION DATETIME DEFAULT GETDATE(),
    ULTIMO_ACCESO DATETIME DEFAULT GETDATE(),
    INTENTOS_FALLIDOS INT DEFAULT 0,
    BLOQUEADO_HASTA DATETIME,
    AUD_USUARIO_INGRESO VARCHAR (20) DEFAULT 'SISTEMA',
    AUD_FEC_INGRESO DATETIME DEFAULT GETDATE(),
    AUD_FEC_MODIFICA DATETIME,
    AUD_USUARIO_MODIFICA VARCHAR (20)
);

CREATE INDEX IX_PERSONA_RUT ON SGT_PERSONA_TALLER(RUT_PERSONA);
CREATE INDEX IX_PERSONA_CORREO ON SGT_PERSONA_TALLER(CORREO_ELECTRONICO);
CREATE INDEX IX_PERSONA_TIPO ON SGT_PERSONA_TALLER(TIPO_USUARIO, IND_ACTIVO);

GO

--INSERT INTO SGT_PERSONA_TALLER (RUT_PERSONA,DV_PERSONA,NOMBRE_PERSONA,APELLIDO_PATERNO,APELLIDO_MATERNO,FEC_NACIMIENTO,TELEFONO,CORREO_ELECTRONICO,CALLE,ID_COMUNA,ID_PAIS,CONTRASENA_HASH)
--VALUES (123123,1,'PRUEBA','AP_PRUEBA','AM_PRUEBA','01-08-2001','4444','PRUEBA@GMAIL.COM','WUAP',1,1,'ESQUERE')