USE GESTION_TALLER;

IF OBJECT_ID('AUTENTIFICACION_SIN_HASH', 'P') IS NOT NULL
    DROP PROCEDURE AUTENTIFICACION_SIN_HASH;
GO

CREATE PROCEDURE AUTENTIFICACION_SIN_HASH
    @IDENTIFICADOR VARCHAR(100),
    @CONTRASENA VARCHAR(255)
AS BEGIN
    SET NOCOUNT ON;

    --DECLARE @CONTRASENA_HASH VARCHAR (255)
    --    SET @CONTRASENA_HASH = CONVERT(VARCHAR(255), HASHBYTES('SHA2_256', @CONTRASENA));
    
    DECLARE @ID_FUNCIONARIO NUMERIC(10);
    --DECLARE @TIPO_USUARIO VARCHAR(20);
    DECLARE @NOMBRE_COMPLETO VARCHAR(185);
    --DECLARE @BLOQUEADO BIT;
    --DECLARE @INTENTOS INT;

    SELECT
        @ID_FUNCIONARIO = ID_F,
        --@TIPO_USUARIO = TIPO_USUARIO,
        @NOMBRE_COMPLETO = NOMBRE_F + ' ' + APELLIDO_PATERNO_F + ' ' + APELLIDO_MATERNO_F
        --@BLOQUEADO = CASE WHEN BLOQUEADO_HASTA IS NOT NULL AND BLOQUEADO_HASTA > GETDATE() THEN 1 ELSE 0 END,
        --@INTENTOS = INTENTOS_FALLIDOS
    FROM SGT_PERSONA_FUNCIONARIO
    WHERE (RUT_F = CASE WHEN ISNUMERIC(@IDENTIFICADOR) = 1 THEN CAST(@IDENTIFICADOR AS NUMERIC(10,0)) ELSE NULL END OR CORREO_ELECTRONICO_F = @IDENTIFICADOR);
    --WHERE (RUT_F = CASE WHEN ISNUMERIC(@IDENTIFICADOR) = 1 THEN CAST(@IDENTIFICADOR AS NUMERIC(10,0)) ELSE NULL END OR CORREO_ELECTRONICO = @IDENTIFICADOR) AND IND_ACTIVO = 1;
    --WHERE (RUT_PERSONA = TRY_CAST(@IDENTIFICADOR AS NUMERIC) OR CORREO_ELECTRONICO = @IDENTIFICADOR) AND IND_ACTIVO = 1; 
    --  la base de datos es de 2008 la r2 asi que xd

    IF @ID_FUNCIONARIO IS NULL
    BEGIN
        SELECT 'ERROR' AS STATUS, 'USUARIO NO ENCONTRADO' AS MESSAGE, NULL AS DATOS;
        RETURN;
    END

    --IF @BLOQUEADO = 1
    --BEGIN
    --    SELECT 'ERROR' AS STATUS,
    --    'CUENTA BLOQUEADA TEMPORALMENTE' AS MESSAGE;
    --    RETURN;
    --END

    --IF @INTENTOS >= 3
    --BEGIN
    --    UPDATE SGT_PERSONA_TALLER
    --    SET BLOQUEADO_HASTA = DATEADD(MINUTE, 1, GETDATE())
    --    WHERE ID_PERSONA = @ID_PERSONA;

    --    SELECT 'ERROR' AS STATUS, 'DEMASIADOS INTENTOS, BLOQUEADO POR 1 MINUTO' AS MESSAGE, NULL AS DATOS;
    --    RETURN;
    --END

---- Source - https://stackoverflow.com/a/41015373
---- Posted by Rich Benner, modified by community. See post 'Timeline' for change history
---- Retrieved 2026-02-04, License - CC BY-SA 4.0

--IF EXISTS (SELECT * FROM tblGLUserAccess WHERE GLUserName ='xxxxxxxx') 
--BEGIN
--   SELECT 1 
--END
--ELSE
--BEGIN
--    SELECT 2
--END


    --IF EXISTS (SELECT 1 FROM SGT_PERSONA_FUNCIONARIO WHERE ID_F= @ID_FUNCIONARIO AND CONTRASENA_HASH = @CONTRASENA_HASH)
    --IF EXISTS (SELECT 1 FROM SGT_PERSONA_FUNCIONARIO WHERE ID_F = @ID_FUNCIONARIO)
    --BEGIN
    --    UPDATE SGT_PERSONA_TALLER
    --    SET ULTIMO_ACCESO = GETDATE(),
    --        INTENTOS_FALLIDOS = 0,
    --        BLOQUEADO_HASTA = NULL,
    --        AUD_USUARIO_MODIFICA = 'SISTEMA',
    --        AUD_FEC_MODIFICA = GETDATE()
    --    WHERE ID_PERSONA = @ID_PERSONA;

    --    DECLARE @ID_ROL NUMERIC (10,0);

    --    IF @TIPO_USUARIO = 'ESTUDIANTE'
    --    BEGIN
    --        SELECT @ID_ROL = ID_ESTUDIANTE
    --        FROM SGT_ESTUDIANTE
    --        WHERE ID_PERSONA = @ID_PERSONA;
    --    END

    --    ELSE IF @TIPO_USUARIO = 'PROFESOR'
    --    BEGIN
    --        SELECT @ID_ROL = ID_PROFESOR
    --        FROM SGT_PROFESOR
    --        WHERE ID_PERSONA = @ID_PERSONA;
    --    END

    --    ELSE IF @TIPO_USUARIO = 'ADMIN'
    --    BEGIN
    --        SET @ID_ROL = @ID_PERSONA;
    --    END

    --    SELECT
    --        'BIEN' AS STATUS, 
    --        'AUTENTIFICACION EXITOSA' AS MESSAGE,
    --        @ID_PERSONA AS ID_PERSONA,
    --        @TIPO_USUARIO AS TIPO_USUARIO,
    --        @ID_ROL AS ID_ROL,
    --        @NOMBRE_COMPLETO AS NOMBRE_COMPLETO;
    --    END
        --SELECT 
        --    'BIEN' AS STATUS, 
        --    'AUTENTIFICACION EXITOSA' AS MESSAGE,
        --    JSON_QUERY((
        --        SELECT 
        --            P.ID_PERSONA, 
        --            P.RUT_PERSONA, 
        --            P.DV_PERSONA, 
        --            P.NOMBRE_PERSONA, 
        --            P.APELLIDO_PATERNO, 
        --            P.APELLIDO_MATERNO, 
        --            P.CORREO_ELECTRONICO, 
        --            P.TIPO_USUARIO, 
        --            @ID_ROL AS ID_ROL, 
        --            @NOMBRE_COMPLETO AS NOMBRE_COMPLETO, 
        --            P.TELEFONO, 
        --            P.FEC_NACIMIENTO, 
        --            P.EDAD, 
        --            P.GENERO
        --        FROM SGT_PERSONA_TALLER P
        --        WHERE P.ID_PERSONA = @ID_PERSONA 
        --        FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
        -- )) AS DATOS;

--SELECT JSON_QUERY(@j, '$.credit_cards[*].type' WITH ARRAY WRAPPER);

--SELECT TOP 3 SalesOrderNumber, OrderDate, Status  
--FROM Sales.SalesOrderHeader  
--ORDER BY ModifiedDate  
--FOR JSON PATH, WITHOUT_ARRAY_WRAPPER

        --ELSE
        --BEGIN
        --    UPDATE SGT_PERSONA_TALLER
        --    SET INTENTOS_FALLIDOS = INTENTOS_FALLIDOS + 1,
        --        AUD_USUARIO_INGRESO ='SISTEMA',
        --        AUD_FEC_MODIFICA = GETDATE()
        --        WHERE ID_PERSONA = @ID_PERSONA;
        --        SELECT 'ERROR' AS STATUS, 'CONTRASEÑA INCORRECTA' AS MESSAGE, NULL AS DATOS;
        --END
END;
GO