USE GESTION_TALLER;

IF OBJECT_ID('AUTENTIFICACION', 'P') IS NOT NULL
    DROP PROCEDURE AUTENTIFICACION;
GO

CREATE PROCEDURE AUTENTIFICACION
    --@RUT NUMERIC(10),
    --@DV CHAR(1),
    --@CONTRASEÑA VARCHAR(20)
    @USUARIO VARCHAR(20),
    @PASSWORD VARCHAR(20)

AS BEGIN

SELECT TOP 1
    ID_F,
    NOMBRE_F,
    APELLIDO_PATERNO_F,
    APELLIDO_MATERNO_F
FROM SGT_PERSONA_FUNCIONARIO
WHERE ID_USUARIO_F = @USUARIO
  AND PASSWORD_F = @PASSWORD
END
GO