USE GESTION_TALLER;
GO

IF OBJECT_ID('AUTENTIFICACION_SIMPLE', 'P') IS NOT NULL
    DROP PROCEDURE AUTENTIFICACION_SIMPLE;
GO

CREATE PROCEDURE AUTENTIFICACION_SIMPLE
    @RUT NUMERIC(10),
    @DV CHAR(1),
    @CONTRASENA VARCHAR(255)
AS
BEGIN
    SET NOCOUNT ON;

    --DECLARE @ID_F NUMERIC(10);
    --DECLARE @NOMBRE_COMPLETO VARCHAR(185);
    --DECLARE @PASS_BD VARCHAR(255);

    SELECT TOP 1
        ID_F,
        NOMBRE_F,
        APELLIDO_PATERNO_F,
        APELLIDO_MATERNO_F,
        CORREO_ELECTRONICO_F,
        RUT_F,
        DV_F
    FROM SGT_PERSONA_FUNCIONARIO
    WHERE RUT_F = @RUT
      AND LOWER(DV_F) = LOWER(@DV)
      AND PASSWORD_F = @CONTRASENA

    --SELECT 
    --    @ID_F = ID_F,
    --    @NOMBRE_COMPLETO = RTRIM(NOMBRE_F) + ' ' + RTRIM(APELLIDO_PATERNO_F) + ' ' + ISNULL(RTRIM(APELLIDO_MATERNO_F), ''),
    --    @PASS_BD = PASSWORD_F
    --FROM SGT_PERSONA_FUNCIONARIO
    --WHERE RUT_F = @RUT AND DV_F = @DV;

    --IF @ID_F IS NULL
    --BEGIN
    --    SELECT 0 AS EXITO, 'USUARIO_NO_ENCONTRADO' AS MENSAJE, NULL AS ID_F, NULL AS NOMBRE;
    --    RETURN;
    --END

    --IF @PASS_BD = @CONTRASENA
    --BEGIN
    --    SELECT 1 AS EXITO, 'OK' AS MENSAJE, @ID_F AS ID_F, @NOMBRE_COMPLETO AS NOMBRE;
    --END
    --ELSE
    --BEGIN
    --    SELECT 0 AS EXITO, 'CONTRASENA_INCORRECTA' AS MENSAJE, NULL AS ID_F, NULL AS NOMBRE;
    --END

    --    SELECT TOP 1
    --        P.ID_PERSONA,
    --        P.NOMBRE_PERSONA,
    --        P.APELLIDO_PATERNO,
    --        P.APELLIDO_MATERNO,
    --        P.CORREO_ELECTRONICO,
    --        P.TIPO_USUARIO,
    --        P.RUT_PERSONA,
    --        P.DV_PERSONA
    --    FROM SGT_PERSONA_TALLER P
    --    WHERE P.RUT_PERSONA = ?
    --        AND LOWER(P.DV_PERSONA) = LOWER(?)
    --        AND P.CONTRASENA_HASH = ?
    --        AND P.IND_ACTIVO = 1

END;
GO