USE GESTION_TALLER;

IF OBJECT_ID('AUTENTIFICACION_SIN_HASH', 'P') IS NOT NULL
    DROP PROCEDURE AUTENTIFICACION_SIN_HASH;
GO

-- esta autentificacion utiliza al sgt_persona_funcionario en vez del persona taller, la idea es que los funcionarios esten en un apartado distinto y que los profesores con estudiantes esten todos en la misma tabla, desde alli se filtra
-- proximamente como solo pueden ser profesores y estudiantes estaba pensando que tal vez podria ponerles por bit, 0 estudiantes y 1 profesores

USE GESTION_TALLER;
GO

IF OBJECT_ID('AUTENTIFICACION_SIN_HASH', 'P') IS NOT NULL
    DROP PROCEDURE AUTENTIFICACION_SIN_HASH;
GO

CREATE PROCEDURE AUTENTIFICACION_SIN_HASH
    @RUT NUMERIC(10),
    @DV CHAR(1),
    @CONTRASENA VARCHAR(255)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @ID_F NUMERIC(10);
    DECLARE @NOMBRE_COMPLETO VARCHAR(185);
    DECLARE @PASS_BD VARCHAR(255);

    SELECT 
        @ID_F = ID_F,
        @NOMBRE_COMPLETO = RTRIM(NOMBRE_F) + ' ' + RTRIM(APELLIDO_PATERNO_F) + ' ' + ISNULL(RTRIM(APELLIDO_MATERNO_F), ''),
        @PASS_BD = PASSWORD_F
    FROM SGT_PERSONA_FUNCIONARIO
    WHERE RUT_F = @RUT AND DV_F = @DV;

    IF @ID_F IS NULL
    BEGIN
        SELECT 0 AS EXITO, 'USUARIO_NO_ENCONTRADO' AS MENSAJE, NULL AS ID_F, NULL AS NOMBRE;
        RETURN;
    END

    IF @PASS_BD = @CONTRASENA
    BEGIN
        SELECT 1 AS EXITO, 'OK' AS MENSAJE, @ID_F AS ID_F, @NOMBRE_COMPLETO AS NOMBRE;
    END
    ELSE
    BEGIN
        SELECT 0 AS EXITO, 'CONTRASENA_INCORRECTA' AS MENSAJE, NULL AS ID_F, NULL AS NOMBRE;
    END

--CREATE PROCEDURE AUTENTIFICACION_SIN_HASH
--    @RUT NUMERIC(10),
--    @DV CHAR(1),
--    @CONTRASENA VARCHAR(255)
--AS
--BEGIN
--    SET NOCOUNT ON;

--    DECLARE @ID_F NUMERIC(10);
--    DECLARE @NOMBRE_COMPLETO VARCHAR(185);
--    DECLARE @PASSWORD_ALMACENADA VARCHAR(255);

--    SELECT 
--        @ID_F = ID_F,
--        @NOMBRE_COMPLETO = RTRIM(NOMBRE_F) + ' ' + RTRIM(APELLIDO_PATERNO_F) + ' ' + ISNULL(RTRIM(APELLIDO_MATERNO_F), ''),
--        @PASSWORD_ALMACENADA = PASSWORD_F
--    FROM SGT_PERSONA_FUNCIONARIO
--    WHERE RUT_F = @RUT AND DV_F = @DV;

--    IF @ID_F IS NULL
--    BEGIN
--        SELECT 0 AS EXITO, 'Usuario no encontrado' AS MENSAJE, NULL AS ID_F, NULL AS NOMBRE;
--        RETURN;
--    END

--    IF @PASSWORD_ALMACENADA = @CONTRASENA
--    BEGIN
--        SELECT 1 AS EXITO, 'OK' AS MENSAJE, @ID_F AS ID_F, @NOMBRE_COMPLETO AS NOMBRE;
--    END
--    ELSE
--    BEGIN
--        SELECT 0 AS EXITO, 'Contraseña incorrecta' AS MENSAJE, NULL AS ID_F, NULL AS NOMBRE;
--    END

-- Source - https://stackoverflow.com/a/64647895
-- Posted by Gordon Prince
-- Retrieved 2026-04-27, License - CC BY-SA 4.0

--SELECT * 
--FROM x 
--WHERE CONDITION1
--AND ((@pol IS NOT NULL AND x.PolicyNo = @pol) OR (@st IS NOT NULL AND x.State = @st))
--AND OTHERCONDITIONS


--AS BEGIN
--    SET NOCOUNT ON;
    
--    DECLARE @ID_FUNCIONARIO NUMERIC(10);
--    DECLARE @NOMBRE_COMPLETO VARCHAR(185);

--    SELECT
--        @ID_FUNCIONARIO = ID_F,
--        @NOMBRE_COMPLETO = NOMBRE_F + ' ' + APELLIDO_PATERNO_F + ' ' + APELLIDO_MATERNO_F
--    FROM SGT_PERSONA_FUNCIONARIO
--    WHERE (RUT_F = CASE WHEN ISNUMERIC(@IDENTIFICADOR) = 1 THEN CAST(@IDENTIFICADOR AS NUMERIC(10,0)) ELSE NULL END OR CORREO_ELECTRONICO_F = @IDENTIFICADOR)
--      AND (RUT_F IS NOT NULL AND @DV IS NOT NULL ;

--SELECT *
--FROM YourTable
--WHERE a = 'hi' 
--  AND (a IS NOT NULL AND b = 'hi');


    --IF @ID_FUNCIONARIO IS NULL
    --BEGIN
    --    SELECT 'ERROR' AS STATUS, 'USUARIO NO ENCONTRADO' AS MESSAGE, NULL AS DATOS;
    --    RETURN;
    --END

END;
GO