USE GESTION_TALLER;

IF OBJECT_ID('INSCRIBIR_TALLER_O_ESPERA', 'P') IS NOT NULL
    DROP PROCEDURE INSCRIBIR_TALLER_O_ESPERA;
GO

CREATE PROCEDURE INSCRIBIR_TALLER_O_ESPERA
    @ID_TALLER NUMERIC(10),
    @ID_ESTUDIANTE NUMERIC(10),
    @YEAR_PROCESO INT,
    @AUD_USUARIO_INGRESO VARCHAR (20)
AS 
BEGIN
    SET NOCOUNT OFF;
    
    DECLARE @CUPOS_DISPONIBLES INT;
    DECLARE @CUPOS_MAXIMOS INT;
    DECLARE @INSCRITOS INT;
    DECLARE @NUEVO_ID_ESPERA NUMERIC;
    DECLARE @MENSAJE VARCHAR(500);
    DECLARE @EN_LISTA_ESPERA BIT;

    SELECT @CUPOS_MAXIMOS = MAXIMO_ESTUDIANTE 
    FROM SGT_TALLER 
    WHERE ID_TALLER = @ID_TALLER;

    IF @CUPOS_MAXIMOS IS NULL
    BEGIN
        SELECT 'El taller especificado no existe' AS mensaje, 0 AS en_lista_espera, @ID_TALLER AS id_taller, @ID_ESTUDIANTE AS id_estudiante;
        RETURN;
    END

    SELECT @INSCRITOS = COUNT(*) 
    FROM SGT_INTEGRANTE_TALLER 
    WHERE ID_TALLER = @ID_TALLER 
    AND IND_ESTADO_INTEGRANTE = 1;

    SET @CUPOS_DISPONIBLES = @CUPOS_MAXIMOS - @INSCRITOS;
    IF EXISTS (SELECT 1 FROM SGT_INTEGRANTE_TALLER 
               WHERE ID_ESTUDIANTE = @ID_ESTUDIANTE 
               AND ID_TALLER = @ID_TALLER
               AND IND_ESTADO_INTEGRANTE = 1)
    BEGIN
        SET @MENSAJE = 'El estudiante ya está inscrito en este taller';
        SET @EN_LISTA_ESPERA = 0;
    END
    ELSE IF @CUPOS_DISPONIBLES > 0
    BEGIN
        INSERT INTO SGT_INTEGRANTE_TALLER (ID_TALLER, ID_ESTUDIANTE, YEAR_PROCESO, IND_ESTADO_INTEGRANTE, FEC_INSCRIPCION, FEC_RETIRO, OBSERVACION, FEC_REINCORPORACION, AUD_USUARIO_INGRESO, AUD_FEC_INGRESO, AUD_USUARIO_MODIFICA, AUD_FEC_MODIFICA) 
        VALUES (@ID_TALLER, @ID_ESTUDIANTE, @YEAR_PROCESO,1, GETDATE(), '1900-01-01 00:00:00.000', '-', '1900-01-01 00:00:00.000',@AUD_USUARIO_INGRESO, GETDATE(), 'SISTEMA', '1900-01-01 00:00:00.000');
        SET @MENSAJE = 'Inscripción exitosa';
        SET @EN_LISTA_ESPERA = 0;
    END
    ELSE
    BEGIN
        IF OBJECT_ID('SGT_LISTA_ESPERA', 'U') IS NOT NULL
        BEGIN
            INSERT INTO SGT_LISTA_ESPERA (ID_TALLER, ID_ESTUDIANTE, YEAR_PROCESO,IND_ESTADO_INTEGRANTE, FECHA_ESPERA, ESTADO) 
            VALUES (@ID_TALLER, @ID_ESTUDIANTE, @YEAR_PROCESO,1, GETDATE(), 'En Espera');
            SET @NUEVO_ID_ESPERA = SCOPE_IDENTITY();
            SET @MENSAJE = 'No hay cupos disponibles. Estudiante agregado a lista de espera (ID: ' + CAST(@NUEVO_ID_ESPERA AS VARCHAR) + ')';
            SET @EN_LISTA_ESPERA = 1;
        END
        ELSE
        BEGIN
            SET @MENSAJE = 'No hay cupos disponibles en el taller';
            SET @EN_LISTA_ESPERA = 1;
        END
    END;
    SELECT @MENSAJE AS mensaje, @EN_LISTA_ESPERA AS en_lista_espera, @ID_TALLER AS id_taller, @ID_ESTUDIANTE AS id_estudiante;
END;
GO