USE GESTION_TALLER;
GO

-- ESTE PROCEDIMIENTO SERVIRA PARA CAMBIAR EL ESTADO DE TALLER, LA IDEA ES QUE ESTO SE UTILICE PARA "ELIMINAR EL TALLER" CAMBIANDO EL ESTADO DE TALLER A 4 QUE ES DE CERRADO
IF OBJECT_ID('DE_BAJA_ESTADO_TALLER', 'P') IS NOT NULL
    DROP PROCEDURE DE_BAJA_ESTADO_TALLER;
GO

CREATE PROCEDURE DE_BAJA_ESTADO_TALLER
    @ID_TALLER INT,
    @AUD_USUARIO_MODIFICA VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    
    UPDATE SGT_TALLER
    SET 
        ID_ESTADO_TALLER = 4,
        FEC_ESTADO_TALLER = GETDATE(),
        AUD_USUARIO_MODIFICA = @AUD_USUARIO_MODIFICA,
        AUD_FEC_MODIFICA = GETDATE()
    WHERE ID_TALLER = @ID_TALLER;
    
    SELECT 'Estado del taller actualizado' AS RESULTADO;
END;
GO