USE GESTION_TALLER;

IF OBJECT_ID('BORRAR_TALLER', 'P') IS NOT NULL
    DROP PROCEDURE BORRAR_TALLER;
GO

CREATE PROCEDURE BORRAR_TALLER
	@ID_TALLER NUMERIC(10)
AS BEGIN
	DELETE FROM SGT_TALLER
	WHERE ID_TALLER=@ID_TALLER;
	SELECT 'Los datos del taller fueron eliminados' AS RESULTADO;
END;