USE GESTION_TALLER;

IF OBJECT_ID('BORRAR_ESTUDIANTE', 'P') IS NOT NULL
    DROP PROCEDURE BORRAR_ESTUDIANTE;
GO

CREATE PROCEDURE BORRAR_ESTUDIANTE --puede que no lo vuelva a usar, en vez de borrar estudiantes de los talleres, seria mejor colocarlos como inactivos, almacen de datos.
 @ID_ESTUDIANTE NUMERIC(10),
 @ID_TALLER NUMERIC(10)
AS BEGIN
	DELETE FROM SGT_INTEGRANTE_TALLER
	WHERE ID_ESTUDIANTE=@ID_ESTUDIANTE
	AND (@ID_TALLER IS NULL OR ID_TALLER=@ID_TALLER);

    DELETE FROM SGT_LISTA_ESPERA
    WHERE ID_ESTUDIANTE=@ID_ESTUDIANTE
    AND ID_TALLER=@ID_TALLER;

    IF @@ROWCOUNT > 0
        SELECT 'Probando wuaaa '+CAST(@ID_ESTUDIANTE AS VARCHAR) AS RESULTADO;
    ELSE
        SELECT 'En caso de que no funcione sale este mensaje '+CAST(@ID_ESTUDIANTE AS VARCHAR) AS RESULTADO;
END