USE [GESTION_TALLER]
GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [dbo].[LISTAR_TALLERISTAS_FILTRADOS] 
    @ID_PROFESOR NUMERIC(10) = NULL,
    @NOMBRE_COMPLETO VARCHAR(153) = NULL,
    --@NOMBRE_PERSONA VARCHAR(50) = NULL,
    @ID_TALLER INT = NULL,
    @NOMBRE_TALLER VARCHAR(80) = NULL,
    @PROFESION VARCHAR(500) = NULL,
    --@APELLIDO_PATERNO VARCHAR(50) = NULL,
    --@APELLIDO_MATERNO VARCHAR(50) = NULL,
    @CORREO_ELECTRONICO VARCHAR(100) = NULL
AS 
BEGIN

    SET NOCOUNT ON;
    SELECT PR.ID_PROFESOR, PT.NOMBRE_PERSONA + ' ' + PT.APELLIDO_PATERNO + ' ' + PT.APELLIDO_MATERNO AS NOMBRE_COMPLETO, T.ID_TALLER, T.NOMBRE_TALLER, PR.PROFESION, PT.CORREO_ELECTRONICO
    FROM SGT_PROFESOR PR
         LEFT JOIN SGT_GESTION_TALLER G ON PR.ID_PROFESOR = G.ID_PROFESOR
         LEFT JOIN SGT_TALLER T ON G.ID_TALLER = T.ID_TALLER
         LEFT JOIN SGT_PERSONA_TALLER PT ON PR.ID_PERSONA = PT.ID_PERSONA

    WHERE (@ID_PROFESOR IS NULL OR PR.ID_PROFESOR = @ID_PROFESOR)
      --intentare hacer que cuando se busque por nombre completo (nombre + apellidos) este busque en esas 3 variables
      --AND (@NOMBRE_PERSONA IS NULL OR PT.NOMBRE_PERSONA LIKE '%' + PT.NOMBRE_PERSONA + '%')
      --AND (@APELLIDO_PATERNO IS NULL OR PT.APELLIDO_PATERNO LIKE '%' + PT.APELLIDO_PATERNO + '%')
      --AND (@APELLIDO_MATERNO IS NULL OR PT.APELLIDO_MATERNO LIKE '%' + PT.APELLIDO_MATERNO + '%')
      AND (ISNULL(PT.NOMBRE_PERSONA, '') + ' ' + ISNULL (PT.APELLIDO_PATERNO, '') + ' ' + ISNULL(PT.APELLIDO_MATERNO, '')) LIKE ''
      AND (@CORREO_ELECTRONICO IS NULL OR PT.CORREO_ELECTRONICO LIKE '%' + PT.CORREO_ELECTRONICO + '%')
      AND (@PROFESION IS NULL OR PR.PROFESION LIKE '%' + PR.PROFESION + '%')
      AND (@ID_TALLER IS NULL OR G.ID_TALLER = @ID_TALLER)
      AND (@NOMBRE_TALLER IS NULL OR T.NOMBRE_TALLER LIKE '%' + T.NOMBRE_TALLER + '%')

    ORDER BY PR.ID_PROFESOR DESC;

END;
GO


