USE GESTION_TALLER;

IF OBJECT_ID('BUSCAR_TALLERES', 'P') IS NOT NULL
    DROP PROCEDURE BUSCAR_TALLERES;
GO

CREATE PROCEDURE BUSCAR_TALLERES
    @NOMBRE_TALLER VARCHAR(80),
    @ID_CATEGORIA INT,
    @YEAR_PROCESO INT,
    @ID_ESTADO_TALLER INT,
    @LIMITE INT = 100
AS
BEGIN
    SET NOCOUNT ON;
    
    SELECT TOP (@LIMITE) *
    FROM SGT_TALLER
    WHERE (@NOMBRE_TALLER IS NULL OR NOMBRE_TALLER LIKE '%' + @NOMBRE_TALLER + '%' OR LUGAR LIKE '%' + @NOMBRE_TALLER + '%')
      AND (@ID_CATEGORIA IS NULL OR ID_CATEGORIA = @ID_CATEGORIA)
      AND (@YEAR_PROCESO IS NULL OR YEAR_PROCESO = @YEAR_PROCESO)
      AND ID_ESTADO_TALLER = @ID_ESTADO_TALLER
    ORDER BY FEC_INICIO DESC;
END;
GO