use GESTION_TALLER;

SELECT 
    --   A.ID_ESTUDIANTE,
    --   A.AUD_USUARIO_INGRESO AS 'ESTUDIANTE USUARIO',
	   --A.AUD_FEC_INGRESO  AS 'ESTUDIANTE FECHA',
	   --A.AUD_USUARIO_MODIFICA,
	   --A.AUD_FEC_MODIFICA
	   --E.AUD_USUARIO_INGRESO,
	   --E.AUD_FEC_INGRESO,
	   --E.AUD_USUARIO_MODIFICA,
	   --E.AUD_FEC_MODIFICA,
	   I.ID_ESTUDIANTE,
	   I.AUD_USUARIO_INGRESO,
	   I.AUD_FEC_INGRESO,
	   I.AUD_USUARIO_MODIFICA,
	   I.AUD_FEC_MODIFICA,
	   O.NOMBRE_TALLER,
	   O.ID_TALLER,
	   O.AUD_USUARIO_INGRESO,
	   O.AUD_FEC_INGRESO,
	   O.AUD_USUARIO_MODIFICA,
	   O.AUD_FEC_MODIFICA
FROM SGT_ESTUDIANTE A
	 --LEFT JOIN SGT_PERSONA_TALLER E ON A.ID_PERSONA = E.ID_PERSONA
	 LEFT JOIN SGT_INTEGRANTE_TALLER I ON A.ID_ESTUDIANTE = I.ID_ESTUDIANTE
     LEFT JOIN SGT_TALLER O ON I.ID_TALLER = O.ID_TALLER

WHERE A.ID_ESTUDIANTE=1;