USE GESTION_TALLER;

IF OBJECT_ID('LISTAR_TALLERISTAS_FILTRADOS', 'P') IS NOT NULL
    DROP PROCEDURE LISTAR_TALLERISTAS_FILTRADOS;
GO

CREATE PROCEDURE LISTAR_TALLERISTAS_FILTRADOS 
    @ID_PROFESOR NUMERIC(10) = NULL,
    @NOMBRE_COMPLETO VARCHAR(153) = NULL,
    @ID_TALLER INT = NULL,
    @NOMBRE_TALLER VARCHAR(80) = NULL,
    @PROFESION VARCHAR(500) = NULL,
    @CORREO_ELECTRONICO VARCHAR(100) = NULL
AS 
BEGIN
    SET NOCOUNT ON;

    WITH ULTIMO AS (SELECT PR.ID_PROFESOR, PT.NOMBRE_PERSONA, PT.APELLIDO_PATERNO, PT.APELLIDO_MATERNO, T.ID_TALLER, T.NOMBRE_TALLER, PR.PROFESION, PT.CORREO_ELECTRONICO,
            ROW_NUMBER() OVER (
                PARTITION BY PR.ID_PROFESOR 
                ORDER BY T.AUD_FEC_INGRESO DESC, T.ID_TALLER DESC
            ) AS FINAL
        FROM SGT_PROFESOR PR
        LEFT JOIN SGT_PERSONA_TALLER PT ON PR.ID_PERSONA = PT.ID_PERSONA
        LEFT JOIN SGT_GESTION_TALLER G ON PR.ID_PROFESOR = G.ID_PROFESOR
        LEFT JOIN SGT_TALLER T ON G.ID_TALLER = T.ID_TALLER
        WHERE (@ID_PROFESOR IS NULL OR PR.ID_PROFESOR = @ID_PROFESOR)
          AND (@NOMBRE_COMPLETO IS NULL OR (PT.NOMBRE_PERSONA + ' ' + PT.APELLIDO_PATERNO + ' ' + ISNULL(PT.APELLIDO_MATERNO, '')) LIKE '%' + @NOMBRE_COMPLETO + '%')
          AND (@CORREO_ELECTRONICO IS NULL OR PT.CORREO_ELECTRONICO LIKE '%' + @CORREO_ELECTRONICO + '%')
          AND (@PROFESION IS NULL OR PR.PROFESION LIKE '%' + @PROFESION + '%')
          AND (@ID_TALLER IS NULL OR G.ID_TALLER = @ID_TALLER)
          AND (@NOMBRE_TALLER IS NULL OR T.NOMBRE_TALLER LIKE '%' + @NOMBRE_TALLER + '%')
    )
    SELECT ID_PROFESOR, NOMBRE_PERSONA + ' ' + APELLIDO_PATERNO + ' ' + ISNULL(APELLIDO_MATERNO, '') AS NOMBRE_COMPLETO, ID_TALLER, NOMBRE_TALLER, PROFESION, CORREO_ELECTRONICO
    FROM ULTIMO
    WHERE FINAL = 1
    ORDER BY ID_PROFESOR DESC;
END;