USE GESTION_TALLER;
GO

IF OBJECT_ID('LISTAR_TALLERES_FILTRADOS', 'P') IS NOT NULL
    DROP PROCEDURE LISTAR_TALLERES_FILTRADOS;
GO

CREATE PROCEDURE LISTAR_TALLERES_FILTRADOS
    @YEAR_PROCESO INT = NULL,
    @ID_CATEGORIA INT = NULL,
    @ID_ESTADO_TALLER INT = NULL,
    @ID_TALLER INT = NULL,
    @LUGAR VARCHAR(100) = NULL,
    @NOMBRE_TALLER VARCHAR(80) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    
    SELECT *
    FROM SGT_TALLER
    WHERE (@YEAR_PROCESO IS NULL OR YEAR_PROCESO = @YEAR_PROCESO)
      AND (@ID_CATEGORIA IS NULL OR ID_CATEGORIA = @ID_CATEGORIA)
      AND (@ID_ESTADO_TALLER IS NULL OR ID_ESTADO_TALLER = @ID_ESTADO_TALLER)
      AND (@ID_TALLER IS NULL OR ID_TALLER = @ID_TALLER)
      AND (@LUGAR IS NULL OR LUGAR LIKE '%' + @LUGAR + '%')
      AND (@NOMBRE_TALLER IS NULL OR NOMBRE_TALLER LIKE '%' + @NOMBRE_TALLER + '%')
    ORDER BY ID_TALLER DESC;
    PRINT '@YEAR_PROCESO: ' + ISNULL(CAST(@YEAR_PROCESO AS VARCHAR), 'NULL');
    PRINT '@NOMBRE_TALLER: ' + ISNULL(@NOMBRE_TALLER, 'NULL');

END;
GO