USE GESTION_TALLER;
GO

IF OBJECT_ID('LISTAR_ESTUDIANTES', 'P') IS NOT NULL
    DROP PROCEDURE LISTAR_ESTUDIANTES; --se tiene que colocar una fecha y ind de estado para filtrar
GO

CREATE PROCEDURE LISTAR_ESTUDIANTES
    @ID_ESTUDIANTE INT,
    --@ID_TALLER INT,
    @NOMBRE_COMPLETO VARCHAR(153),
    @CORREO_ELECTRONICO VARCHAR(100),
    @ESTADO INT,
    --@FECHA_INSCRIPCION DATETIME,
    @NOMBRE_TALLER VARCHAR(80),
    @YEAR_PROCESO INT
AS
BEGIN

--id_estudiante: '', 
--// id_taller: '',
--nombre_completo: '',
--correo_electronico: '',
--estado: '',
--nombre_taller: '',
--year_proceso: '',
--fecha_inscripcion: ''

    SET NOCOUNT ON;

    WITH ULTIMO AS (SELECT A.ID_ESTUDIANTE, I.NOMBRE_PERSONA, I.APELLIDO_PATERNO, I.APELLIDO_MATERNO, E.IND_ESTADO_INTEGRANTE, O.ID_TALLER, O.NOMBRE_TALLER, E.FEC_INSCRIPCION, E.YEAR_PROCESO, I.CORREO_ELECTRONICO, ROW_NUMBER() OVER (PARTITION BY A.ID_ESTUDIANTE ORDER BY O.AUD_FEC_INGRESO DESC, O.ID_TALLER DESC) AS FINAL
        FROM SGT_ESTUDIANTE A
        LEFT JOIN SGT_INTEGRANTE_TALLER E ON A.ID_ESTUDIANTE = E.ID_ESTUDIANTE
        LEFT JOIN SGT_PERSONA_TALLER I ON A.ID_PERSONA = I.ID_PERSONA
        LEFT JOIN SGT_TALLER O ON E.ID_TALLER = O.ID_TALLER
        WHERE (@ID_ESTUDIANTE IS NULL OR A.ID_ESTUDIANTE = @ID_ESTUDIANTE)
          AND (@NOMBRE_COMPLETO IS NULL OR (I.NOMBRE_PERSONA + ' ' + I.APELLIDO_PATERNO + ' ' + ISNULL(I.APELLIDO_MATERNO, '')) LIKE '%' + @NOMBRE_COMPLETO + '%')
          AND (@CORREO_ELECTRONICO IS NULL OR I.CORREO_ELECTRONICO LIKE '%' + @CORREO_ELECTRONICO + '%')
          AND (@ESTADO IS NULL OR E.IND_ESTADO_INTEGRANTE = @ESTADO)
          --AND (@FECHA_INSCRIPCION IS NULL OR E.FEC_INSCRIPCION = @FECHA_INSCRIPCION)
          AND (@NOMBRE_TALLER IS NULL OR O.NOMBRE_TALLER LIKE '%' + @NOMBRE_TALLER + '%')
          AND (@YEAR_PROCESO IS NULL OR E.YEAR_PROCESO = @YEAR_PROCESO)
    )
    SELECT ID_ESTUDIANTE, NOMBRE_PERSONA + ' ' + APELLIDO_PATERNO + ' ' + ISNULL(APELLIDO_MATERNO, '') AS NOMBRE_COMPLETO, IND_ESTADO_INTEGRANTE, ID_TALLER, NOMBRE_TALLER, YEAR_PROCESO, CORREO_ELECTRONICO, FEC_INSCRIPCION
    FROM ULTIMO
    WHERE FINAL = 1
    ORDER BY ID_ESTUDIANTE DESC;

END;
GO