USE GESTION_TALLER;

IF OBJECT_ID('LISTAR_TALLERISTAS_FILTRADOS', 'P') IS NOT NULL
    DROP PROCEDURE LISTAR_TALLERISTAS_FILTRADOS;
GO

CREATE PROCEDURE LISTAR_TALLERISTAS_FILTRADOS 
    @ID_PROFESOR NUMERIC(10) = NULL,
    @NOMBRE_COMPLETO VARCHAR(153) = NULL,
    @ID_TALLER INT = NULL,
    @NOMBRE_TALLER VARCHAR(80) = NULL,
    @PROFESION VARCHAR(500) = NULL,
    @CORREO_ELECTRONICO VARCHAR(100) = NULL
AS 
BEGIN

    --para que se entienda que esta sucediendo aqui, primero meto todo el select con los filtros en caso de NULLS en el where, hago todo esto para hacer uso del ROW_NUMBER, esto es asi por que los profesores tienen mas de un taller en su historial y quiero que la lista despliegue
    --solo los ultimos talleres en los cuales estan , esto solo toma en cuenta la fecha de AUD_FEC_INGRESO, 

    SET NOCOUNT ON;
    WITH ULTIMO AS (SELECT PR.ID_PROFESOR, PT.NOMBRE_PERSONA, PT.APELLIDO_PATERNO, PT.APELLIDO_MATERNO, T.ID_TALLER, T.NOMBRE_TALLER, PR.PROFESION, PT.CORREO_ELECTRONICO, T.AUD_FEC_INGRESO, ROW_NUMBER() OVER (PARTITION BY PR.ID_PROFESOR ORDER BY T.AUD_FEC_INGRESO DESC, T.ID_TALLER DESC) AS FINAL
    FROM SGT_PROFESOR PR
         LEFT JOIN SGT_PERSONA_TALLER PT ON PR.ID_PERSONA = PT.ID_PERSONA
         LEFT JOIN SGT_GESTION_TALLER G ON PR.ID_PROFESOR = G.ID_PROFESOR
         LEFT JOIN SGT_TALLER T ON G.ID_TALLER = T.ID_TALLER

    --WHERE PR.ID_PROFESOR = 129)

    WHERE (@ID_PROFESOR IS NULL OR PR.ID_PROFESOR = @ID_PROFESOR)
      AND (@NOMBRE_COMPLETO IS NULL OR (PT.NOMBRE_PERSONA + ' ' + PT.APELLIDO_PATERNO + ' ' + PT.APELLIDO_MATERNO) LIKE '%' + @NOMBRE_COMPLETO + '%')
      AND (@CORREO_ELECTRONICO IS NULL OR PT.CORREO_ELECTRONICO LIKE '%' + PT.CORREO_ELECTRONICO + '%')
      AND (@PROFESION IS NULL OR PR.PROFESION LIKE '%' + PR.PROFESION + '%')
      AND (@ID_TALLER IS NULL OR G.ID_TALLER = NULL)
      AND (@NOMBRE_TALLER IS NULL OR T.NOMBRE_TALLER LIKE '%' + T.NOMBRE_TALLER + '%')
    )

    SELECT ID_PROFESOR, NOMBRE_PERSONA + ' ' + APELLIDO_PATERNO + ' ' + APELLIDO_MATERNO AS NOMBRE_COMPLETO, ID_TALLER, NOMBRE_TALLER, PROFESION, CORREO_ELECTRONICO
    FROM ULTIMO
    WHERE FINAL = 1

    ORDER BY ID_PROFESOR DESC;

END;