IF OBJECT_ID('LISTAR_ESTUDIANTES_POR_TALLER', 'P') IS NOT NULL
    DROP PROCEDURE LISTAR_ESTUDIANTES_POR_TALLER;
GO

CREATE PROCEDURE LISTAR_ESTUDIANTES_POR_TALLER
    @ID_TALLER INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT 
        IT.ID_ESTUDIANTE,
        P.NOMBRE_PERSONA,
        P.APELLIDO_PATERNO,
        P.APELLIDO_MATERNO
    FROM SGT_INTEGRANTE_TALLER IT
    INNER JOIN SGT_PERSONA_TALLER P ON IT.ID_ESTUDIANTE = P.ID_PERSONA
    WHERE IT.ID_TALLER = @ID_TALLER
      AND IT.IND_ESTADO_INTEGRANTE = 1;
END;
GO