USE GESTION_TALLER;
GO

IF OBJECT_ID('OBTENER_HISTORIAL_TALLERES_TALLERISTA', 'P') IS NOT NULL
    DROP PROCEDURE OBTENER_HISTORIAL_TALLERES_TALLERISTA;
GO

CREATE PROCEDURE OBTENER_HISTORIAL_TALLERES_TALLERISTA
    @ID_PROFESOR INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT 
        O.ID_PROFESOR,
        A.ID_TALLER,
        A.NOMBRE_TALLER,
        A.OBJETIVO_TALLER,
        A.OBSERVACION,
        A.YEAR_PROCESO,
        A.FEC_INICIO,
        A.FEC_TERMINO,
        E.DESCRIPCION_ESTADO_TALLER, 
        E.ID_ESTADO_TALLER
        --CASE WHEN A.ID_ESTADO_TALLER IN (1) THEN 'Activo' ELSE 'Inactivo' END AS ESTADO_ACTUAL
    FROM SGT_TALLER A
    LEFT JOIN SGT_ESTADO_TALLER E ON A.ID_ESTADO_TALLER = E.ID_ESTADO_TALLER
    LEFT JOIN SGT_GESTION_TALLER I ON A.ID_TALLER = I.ID_TALLER
    LEFT JOIN SGT_PROFESOR O ON I.ID_PROFESOR = O.ID_PROFESOR
    WHERE O.ID_PROFESOR = @ID_PROFESOR
    ORDER BY A.YEAR_PROCESO DESC, A.FEC_INICIO DESC;
END;
GO