USE GESTION_TALLER;
GO

IF OBJECT_ID('OBTENER_ESTUDIANTES_POR_TALLER', 'P') IS NOT NULL
    DROP PROCEDURE OBTENER_ESTUDIANTES_POR_TALLER;
GO

CREATE PROCEDURE OBTENER_ESTUDIANTES_POR_TALLER
    @ID_TALLER INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT 
        IT.ID_ESTUDIANTE,
        ISNULL(P.NOMBRE_PERSONA, 'Sin nombre') AS NOMBRE,
        ISNULL(P.APELLIDO_PATERNO, 'Sin apellido paterno') AS APELLIDO_PATERNO,
        ISNULL(P.APELLIDO_MATERNO, 'Sin apellido materno') AS APELLIDO_MATERNO,
        IT.YEAR_PROCESO,
        IT.FEC_INSCRIPCION
    FROM SGT_INTEGRANTE_TALLER IT
    LEFT JOIN SGT_PERSONA_TALLER P ON IT.ID_ESTUDIANTE = P.ID_PERSONA
    WHERE IT.ID_TALLER = @ID_TALLER
      AND IT.IND_ESTADO_INTEGRANTE = 1
    ORDER BY P.NOMBRE_PERSONA;
END;
GO