USE GESTION_TALLER;

IF OBJECT_ID('VER_PROFESOR_HISTORIAL_TALLERES', 'P') IS NOT NULL
    DROP PROCEDURE VER_PROFESOR_HISTORIAL_TALLERES;
GO

CREATE PROCEDURE VER_PROFESOR_HISTORIAL_TALLERES
@ID_PROFESOR NUMERIC(10)

AS 
BEGIN

SELECT E.NOMBRE_PERSONA,
	   O.ID_TALLER,
	   O.NOMBRE_TALLER,
	   O.ID_ESTADO_TALLER,
	   O.FEC_ESTADO_TALLER,
       O.AUD_USUARIO_INGRESO AS 'USUARIO QUE INGRESO EL TALLER',
	   O.AUD_FEC_INGRESO AS 'FECHA INGRESO DEL TALLER',
       O.AUD_USUARIO_MODIFICA AS 'ULTIMO USUARIO QUE MODIFICO EL TALLER',
	   O.AUD_FEC_MODIFICA AS 'ULTIMA FECHA DE MODIFICACION'
FROM SGT_PROFESOR A
	 LEFT JOIN SGT_PERSONA_TALLER E ON A.ID_PERSONA = E.ID_PERSONA
	 LEFT JOIN SGT_GESTION_TALLER I ON A.ID_PROFESOR = I.ID_PROFESOR
	 LEFT JOIN SGT_TALLER O ON I.ID_TALLER = O.ID_TALLER

WHERE A.ID_PROFESOR = @ID_PROFESOR
--WHERE A.ID_PROFESOR=13;

END;