USE GESTION_TALLER;
GO

IF OBJECT_ID('LISTAR_PAISES', 'P') IS NOT NULL
    DROP PROCEDURE LISTAR_PAISES;
GO

CREATE PROCEDURE LISTAR_PAISES 
    @ID_PAIS NUMERIC(10),
    @NOMBRE_PAIS VARCHAR(255)
    
AS 
BEGIN
    SET NOCOUNT ON;

    SELECT ID_PAIS,NOMBRE_PAIS 
    FROM SGT_PAIS_TALLER
    WHERE ID_PAIS = @ID_PAIS
      AND NOMBRE_PAIS = @NOMBRE_PAIS

END;
GO