USE GESTION_TALLER;

IF OBJECT_ID('VER_PROFESOR', 'P') IS NOT NULL
    DROP PROCEDURE VER_PROFESOR;
GO

CREATE PROCEDURE VER_PROFESOR
@ID_PROFESOR NUMERIC(10)

AS 
BEGIN

SELECT A.ID_PERSONA,
       E.RUT_PERSONA,
       E.DV_PERSONA,
       A.ID_PROFESOR,
       E.NOMBRE_PERSONA,
       E.APELLIDO_PATERNO,
       E.APELLIDO_MATERNO,
       E.FEC_NACIMIENTO,
       E.EDAD,
       E.GENERO,
       E.TELEFONO,
       E.TELEFONO_CONTACTO,
       E.NOMBRE_CONTACTO,
       E.CORREO_CONTACTO,
       E.IND_ACTIVO,
       E.TIPO_USUARIO,
       E.OBSERVACION,
       E.CORREO_ELECTRONICO,
       E.CALLE,
       E.NRO_CALLE,
       E.NRO_BLOCK,
       E.NRO_DPTO,
       E.VILLA,
       E.ID_COMUNA,
       E.ID_PAIS,
	   A.PROFESION,
       E.FEC_CREACION,
       E.ULTIMO_ACCESO,
       E.INTENTOS_FALLIDOS,
       E.BLOQUEADO_HASTA,
	   A.RESUMEN_CURRICULAR,
       A.AUD_USUARIO_INGRESO,
	   A.AUD_FEC_INGRESO,
       A.AUD_USUARIO_MODIFICA,
	   A.AUD_FEC_MODIFICA
FROM SGT_PROFESOR A
	 LEFT JOIN SGT_PERSONA_TALLER E ON A.ID_PERSONA = E.ID_PERSONA
	 LEFT JOIN SGT_GESTION_TALLER I ON A.ID_PROFESOR = I.ID_PROFESOR

WHERE A.ID_PROFESOR=@ID_PROFESOR;

END;