USE GESTION_TALLER;

IF OBJECT_ID('VER_PROFESOR', 'P') IS NOT NULL
    DROP PROCEDURE VER_PROFESOR;
GO

CREATE PROCEDURE VER_PROFESOR --falta actualizar, pero no es prioridad hasta tener primero lo de estudiante terminado
@ID_PROFESOR NUMERIC(10)

AS BEGIN
SELECT E.ID_PERSONA AS 'ID de la persona',E.ID_PROFESOR AS 'ID del profesor',E.PROFESION AS 'Profesion',E.RESUMEN_CURRICULAR AS 'Resumen curricular',I.ID_TALLER AS 'ID del taller',O.NOMBRE_TALLER AS 'Noombre del taller',E.AUD_FEC_INGRESO AS 'Fecha de ingreso',E.AUD_FEC_MODIFICA AS 'Fecha modificada'
FROM SGT_PROFESOR A
INNER JOIN SGT_PROFESOR E
	ON A.ID_PROFESOR=E.ID_PROFESOR
INNER JOIN SGT_GESTION_TALLER I
	ON A.ID_PROFESOR=I.ID_PROFESOR
INNER JOIN SGT_TALLER O
	ON I.ID_TALLER=O.ID_TALLER
WHERE E.ID_PROFESOR=5;

END;