USE GESTION_TALLER;

IF OBJECT_ID('VER_TALLERES', 'P') IS NOT NULL
    DROP PROCEDURE VER_TALLERES;
GO

CREATE PROCEDURE VER_TALLERES
    @ID_TALLER NUMERIC(10)
AS 
BEGIN
    SELECT 
        A.ID_TALLER,
        A.YEAR_PROCESO,
        A.ID_CATEGORIA,
        A.NOMBRE_TALLER,
        A.ID_DEPARTAMENTO,
        A.OBJETIVO_TALLER,
        A.FEC_INICIO,
        A.FEC_TERMINO,
        A.NRO_MINUTOS,
        A.NRO_CLASES_ANUAL,
        A.HORAS_TOTALES,
        A.ID_ESTADO_TALLER,
        A.FEC_ESTADO_TALLER,
        A.OBSERVACION,
        A.LUGAR,
        A.MINIMO_ESTUDIANTE,
        A.MAXIMO_ESTUDIANTE,
        ISNULL((SELECT COUNT(*) FROM SGT_INTEGRANTE_TALLER E WHERE E.ID_TALLER = A.ID_TALLER AND E.IND_ESTADO_INTEGRANTE = 1), 0),
        A.REQUISITO,
        A.EDAD_MINIMA,
        A.EDAD_MAXIMA,
        A.MATERIAL,
        A.IND_TIPO_TALLER,
        I.ID_PROFESOR,
        O.NOMBRE_PERSONA,
        O.APELLIDO_PATERNO,
        O.APELLIDO_MATERNO,
        O.EDAD,
        O.GENERO,
        I.PROFESION,
        A.AUD_USUARIO_INGRESO,
        A.AUD_FEC_INGRESO,
        A.AUD_USUARIO_MODIFICA,
        A.AUD_FEC_MODIFICA,
        E.AUD_USUARIO_INGRESO,
        E.AUD_FEC_INGRESO
    FROM SGT_TALLER A
    LEFT JOIN SGT_GESTION_TALLER E ON A.ID_TALLER = E.ID_TALLER
    LEFT JOIN SGT_PROFESOR I ON E.ID_PROFESOR = I.ID_PROFESOR
    LEFT JOIN SGT_PERSONA_TALLER O ON I.ID_PERSONA = O.ID_PERSONA
    WHERE A.ID_TALLER = @ID_TALLER
END;
GO