USE GESTION_TALLER;

IF OBJECT_ID('VER_ESTUDIANTE', 'P') IS NOT NULL
    DROP PROCEDURE VER_ESTUDIANTE;
GO

CREATE PROCEDURE VER_ESTUDIANTE
@ID_ESTUDIANTE NUMERIC(10)

AS 
BEGIN

SELECT A.ID_PERSONA,
       E.RUT_PERSONA,
       E.DV_PERSONA,
       E.PASAPORTE,
       A.ID_ESTUDIANTE,
       E.NOMBRE_PERSONA,
       E.APELLIDO_PATERNO,
       E.APELLIDO_MATERNO,
       E.FEC_NACIMIENTO,
       E.EDAD,
       E.GENERO,
       E.TELEFONO,
       E.TELEFONO_CONTACTO,
       E.NOMBRE_CONTACTO,
       E.CORREO_CONTACTO,
       E.OBSERVACION,
       E.CORREO_ELECTRONICO,
       E.CALLE,
       E.NRO_CALLE,
       E.NRO_BLOCK,
       E.NRO_DPTO,
       E.VILLA,
       E.ID_COMUNA,
       E.ID_PAIS,
       O.ID_TALLER,
       O.NOMBRE_TALLER,
       O.YEAR_PROCESO,
       I.PRONOM_ESTUDIANTE,
       I.FEC_INSCRIPCION,
       I.FEC_RETIRO,
       I.FEC_REINCORPORACION,
       I.AUD_USUARIO_INGRESO,
	   I.AUD_FEC_INGRESO,
       I.AUD_USUARIO_MODIFICA,
	   I.AUD_FEC_MODIFICA
FROM SGT_ESTUDIANTE A
	 LEFT JOIN SGT_PERSONA_TALLER E ON A.ID_PERSONA = E.ID_PERSONA
	 LEFT JOIN SGT_INTEGRANTE_TALLER I ON A.ID_ESTUDIANTE = I.ID_ESTUDIANTE
     LEFT JOIN SGT_TALLER O ON I.ID_TALLER = O.ID_TALLER

WHERE A.ID_ESTUDIANTE=@ID_ESTUDIANTE;

END;