USE GESTION_TALLER;

IF OBJECT_ID('VER_PROFESOR', 'P') IS NOT NULL
    DROP PROCEDURE VER_PROFESOR;
GO

CREATE PROCEDURE VER_PROFESOR
@ID_PROFESOR NUMERIC(10)

AS 
BEGIN

SELECT A.ID_PERSONA,
       E.RUT_PERSONA,
       E.DV_PERSONA,
       A.ID_PROFESOR,
       E.NOMBRE_PERSONA,
       E.APELLIDO_PATERNO,
       E.APELLIDO_MATERNO,
       E.FEC_NACIMIENTO,
       E.EDAD,
       E.GENERO,
       E.TELEFONO,
       E.TELEFONO_CONTACTO,
       E.NOMBRE_CONTACTO,
       E.CORREO_CONTACTO,
       E.OBSERVACION,
       E.CORREO_ELECTRONICO,
       E.CALLE,
       E.NRO_CALLE,
       E.NRO_BLOCK,
       E.NRO_DPTO,
       E.VILLA,
       E.ID_COMUNA,
       E.ID_PAIS,
	   A.PROFESION,
	   A.RESUMEN_CURRICULAR,
       O.ID_TALLER,
       O.NOMBRE_TALLER,
       O.YEAR_PROCESO,
       O.ID_ESTADO_TALLER,
       A.AUD_USUARIO_INGRESO,
	   A.AUD_FEC_INGRESO,
       A.AUD_USUARIO_MODIFICA,
	   A.AUD_FEC_MODIFICA,
       E.AUD_USUARIO_INGRESO,
	   E.AUD_FEC_INGRESO,
       E.AUD_USUARIO_MODIFICA,
	   E.AUD_FEC_MODIFICA,
       I.AUD_USUARIO_INGRESO,
	   I.AUD_FEC_INGRESO
FROM SGT_PROFESOR A
	 LEFT JOIN SGT_PERSONA_TALLER E ON A.ID_PERSONA = E.ID_PERSONA
	 LEFT JOIN SGT_GESTION_TALLER I ON A.ID_PROFESOR = I.ID_PROFESOR
     LEFT JOIN SGT_TALLER O ON I.ID_TALLER = O.ID_TALLER

WHERE A.ID_PROFESOR = @ID_PROFESOR;

END;