USE [GESTION_TALLER]
GO

SELECT [ID_PROFESOR]
      ,[ID_PERSONA]
      ,[PROFESION]
      ,[RESUMEN_CURRICULAR]
      ,[AUD_USUARIO_INGRESO]
      ,[AUD_FEC_INGRESO]
      ,[AUD_USUARIO_MODIFICA]
      ,[AUD_FEC_MODIFICA]
  FROM [dbo].[SGT_PROFESOR]
  WHERE ID_PROFESOR=1
GO


