USE GESTION_TALLER;

IF OBJECT_ID('VER_TALLERES_TALLERISTAS', 'P') IS NOT NULL
    DROP PROCEDURE VER_TALLERES_TALLERISTAS;
GO

CREATE PROCEDURE VER_TALLERES_TALLERISTAS
    @ID_TALLER NUMERIC(10)
AS 
BEGIN
    SELECT 
        A.ID_TALLER AS 'ID del taller',
        I.ID_PROFESOR AS 'ID del Profesor',
        O.NOMBRE_PERSONA AS 'Nombre del Profesor',
        O.APELLIDO_PATERNO AS 'Apellido Paterno',
        O.APELLIDO_MATERNO AS 'Apellido Materno',
        O.EDAD AS 'Edad',
        O.GENERO AS 'Genero',
        I.PROFESION AS 'Profesion',
        I.AUD_USUARIO_INGRESO AS 'Usuario que ingreso el taller',
        I.AUD_FEC_INGRESO AS 'Fecha del ingreso',
        I.AUD_USUARIO_MODIFICA AS 'Usuario que hizo la ultima modificación',
        I.AUD_FEC_MODIFICA AS 'Fecha de la ultima modificación'
    FROM SGT_TALLER A
    LEFT JOIN SGT_GESTION_TALLER E ON A.ID_TALLER = E.ID_TALLER
    LEFT JOIN SGT_PROFESOR I ON E.ID_PROFESOR = I.ID_PROFESOR
    LEFT JOIN SGT_PERSONA_TALLER O ON I.ID_PERSONA = O.ID_PERSONA
    WHERE A.ID_ESTADO_TALLER IN (1,2,3,4)
      AND A.ID_TALLER = @ID_TALLER
END;
GO