USE GESTION_TALLER;

IF OBJECT_ID('VER_ESTUDIANTE_TALLER', 'P') IS NOT NULL
    DROP PROCEDURE VER_ESTUDIANTE_TALLER;
GO

CREATE PROCEDURE VER_ESTUDIANTE_TALLER
	@ID_ESTUDIANTE NUMERIC(10),
	@ID_TALLER NUMERIC(10) = NULL

AS BEGIN
	SELECT E.ID_TALLER, T.NOMBRE_TALLER, E.ID_ESTUDIANTE, E.YEAR_PROCESO, E.IND_ESTADO_INTEGRANTE, E.FEC_INSCRIPCION, E.FEC_RETIRO, E.OBSERVACION, E.FEC_REINCORPORACION, E.AUD_USUARIO_INGRESO, E.AUD_FEC_INGRESO, E.AUD_USUARIO_MODIFICA, E.AUD_FEC_MODIFICA
	FROM SGT_INTEGRANTE_TALLER E
	INNER JOIN SGT_TALLER T
		ON E.ID_TALLER = T.ID_TALLER
	WHERE E.ID_ESTUDIANTE = @ID_ESTUDIANTE
		AND (@ID_TALLER IS NULL OR E.ID_TALLER = @ID_TALLER)
	ORDER BY E.FEC_INSCRIPCION DESC;
END;